import { StyleSheet } from 'react-native';
import { COLORS, SHADOWS } from '../../constants/theme';

export const ADVISOR_ROLES = [
  { code: 'WORKSHOP_ADMIN', label: 'Owner', color: '#023D95' },
  { code: 'WORKSHOP_SUPERVISOR', label: 'Advisor', color: '#0284C7' },
  { code: 'WORKSHOP_MECHANIC', label: 'Mechanic', color: '#059669' },
  { code: 'WORKSHOP_PICKUP_BOY', label: 'Pickup', color: '#EA580C' },
] as const;

export function advisorRoleStyle(code?: string | null) {
  return (
    ADVISOR_ROLES.find((r) => r.code === code) || {
      code: code || '',
      label: 'Staff',
      color: '#64748B',
    }
  );
}

/** Shared Advisor look — same language as Telecaller CRM / Lead Manager. */
export const AC = StyleSheet.create({
  page: { flex: 1, backgroundColor: COLORS.background },
  sub: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.textSecondary,
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 8,
  },
  kpiRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    justifyContent: 'space-between',
    rowGap: 8,
    marginBottom: 10,
  },
  kpi: {
    width: '23.5%',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 4,
    alignItems: 'center',
    minHeight: 70,
    ...SHADOWS.small,
  },
  kpiWide: {
    width: '48.5%',
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    minHeight: 88,
    ...SHADOWS.small,
  },
  kpiVal: { fontSize: 18, fontWeight: '800' },
  kpiLab: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginTop: 2,
    textAlign: 'center',
  },
  chipWrap: { paddingLeft: 16, marginBottom: 10 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 8,
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: COLORS.border,
    alignSelf: 'flex-start',
    justifyContent: 'center',
  },
  chipOn: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  chipTxt: { fontSize: 12, fontWeight: '800', color: COLORS.textPrimary },
  chipTxtOn: { color: '#fff' },
  navy: {
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    padding: 14,
    marginHorizontal: 16,
    marginBottom: 10,
    ...SHADOWS.small,
  },
  navyName: { fontSize: 15, fontWeight: '800', color: '#fff', flex: 1 },
  navyMeta: { fontSize: 12, color: 'rgba(255,255,255,0.82)', marginTop: 3 },
  navyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
  },
  navySla: { fontSize: 12, fontWeight: '800', color: '#FECACA' },
  navySlaOk: { fontSize: 12, fontWeight: '800', color: '#BBF7D0' },
  navyBadge: {
    alignSelf: 'flex-start',
    marginTop: 8,
    marginRight: 6,
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  navyBadgeTxt: { color: '#fff', fontSize: 10, fontWeight: '800' },
  navyBtnRow: { flexDirection: 'row', gap: 8, marginTop: 12 },
  navyBtn: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  navyBtnTxt: { color: COLORS.primary, fontWeight: '800', fontSize: 13 },
  navyBtnGhost: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  navyBtnGhostTxt: { color: '#fff', fontWeight: '800', fontSize: 13 },
  whiteCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginHorizontal: 16,
    marginBottom: 10,
    ...SHADOWS.small,
  },
  listCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginHorizontal: 16,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
    ...SHADOWS.small,
  },
  btnRow: { flexDirection: 'row', gap: 8, marginTop: 12 },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  statusPillTxt: { color: '#fff', fontSize: 10, fontWeight: '800' },
  name: { fontSize: 16, fontWeight: '800', color: COLORS.textHeading },
  meta: { fontSize: 13, color: COLORS.textSecondary, marginTop: 2 },
  primaryBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  primaryBtnTxt: { color: '#fff', fontWeight: '800', fontSize: 14 },
  empty: { alignItems: 'center', paddingVertical: 48, paddingHorizontal: 24 },
  emptyTxt: { fontSize: 16, fontWeight: '800', color: COLORS.textHeading },
  emptySub: { fontSize: 13, color: COLORS.textSecondary, marginTop: 4, textAlign: 'center' },
  section: {
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.textHeading,
    paddingHorizontal: 16,
    marginBottom: 8,
    marginTop: 4,
  },
});
