'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ExternalLink, RefreshCw, RotateCcw, Save } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { seoAdminTheme as t } from '@/components/admin/site-seo/seo-admin-theme';
import type { LiveFileAdminView, LiveFileKey } from '@/lib/site-seo-live-files';

type Props = {
  compact?: boolean;
};

export default function LiveFilesEditor({ compact = false }: Props) {
  const [files, setFiles] = useState<LiveFileAdminView[]>([]);
  const [selectedKey, setSelectedKey] = useState<LiveFileKey>('robots_txt');
  const [draftContent, setDraftContent] = useState('');
  const [useCustom, setUseCustom] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const selected = useMemo(
    () => files.find((file) => file.file_key === selectedKey) || null,
    [files, selectedKey],
  );

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/super_admin/site-seo/live-files', { cache: 'no-store' });
      const json = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(json?.error || json?.details || json?.hint || 'Failed to load live files');
      const data = (json.data || []) as LiveFileAdminView[];
      setFiles(data);
      setSelectedKey((prev) => (data.some((file) => file.file_key === prev) ? prev : data[0]?.file_key || 'robots_txt'));
    } catch (err: any) {
      toast.error(err?.message || 'Could not load live files');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  useEffect(() => {
    if (!selected) return;
    setDraftContent(selected.use_custom ? selected.content : selected.generated_content);
    setUseCustom(selected.use_custom);
  }, [selected]);

  const save = async () => {
    if (!selected) return;
    setSaving(true);
    try {
      const res = await fetch('/api/super_admin/site-seo/live-files', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          file_key: selected.file_key,
          content: draftContent,
          use_custom: useCustom,
        }),
      });
      const json = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(json?.error || json?.details || json?.hint || 'Save failed');
      const updated = json.data as LiveFileAdminView;
      setFiles((prev) => prev.map((file) => (file.file_key === updated.file_key ? { ...file, ...updated } : file)));
      toast.success(`${selected.label} saved`);
      await load();
    } catch (err: any) {
      toast.error(err?.message || 'Could not save live file');
    } finally {
      setSaving(false);
    }
  };

  const resetToAuto = () => {
    if (!selected) return;
    setUseCustom(false);
    setDraftContent(selected.generated_content);
  };

  if (loading) {
    return <div className={`${t.card} p-8 text-center text-sm ${t.subtitle}`}>Loading live files…</div>;
  }

  if (!files.length) {
    return (
      <div className={`${t.cardMuted} p-8 text-center text-sm ${t.subtitle}`}>
        Live files unavailable.
      </div>
    );
  }

  return (
    <section className={`${t.card} p-5`}>
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h3 className={t.sectionTitle}>Live Files</h3>
          <p className={`mt-1 text-sm ${t.subtitle}`}>
            Edit robots.txt, sitemap.xml, manifest, llms.txt and other crawl files. Auto-generated by default.
          </p>
        </div>
        <button type="button" onClick={() => load()} disabled={loading || saving} className={t.btnGhost}>
          <RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
          Refresh
        </button>
      </div>

      <div className={`mt-4 grid gap-4 ${compact ? '' : 'xl:grid-cols-[260px_1fr]'}`}>
        <div className="space-y-2">
          {files.map((file) => {
            const active = file.file_key === selectedKey;
            return (
              <button
                key={file.file_key}
                type="button"
                onClick={() => setSelectedKey(file.file_key)}
                className={`flex w-full items-center justify-between rounded-xl border px-3 py-3 text-left transition ${
                  active ? t.fileItemActive : t.fileItemInactive
                }`}
              >
                <div>
                  <p className={t.listTitle}>{file.label}</p>
                  <p className={`mt-0.5 text-xs ${t.subtitle}`}>{file.url.replace(/^https?:\/\/[^/]+/, '')}</p>
                </div>
                <span
                  className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${
                    file.use_custom ? 'bg-indigo-50 text-indigo-700 ring-1 ring-indigo-200' : 'bg-slate-100 text-slate-600 ring-1 ring-slate-200'
                  }`}
                >
                  {file.use_custom ? 'Custom' : 'Auto'}
                </span>
              </button>
            );
          })}
        </div>

        {selected ? (
          <div className="space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div>
                <h4 className={`text-base font-black ${t.title}`}>{selected.label}</h4>
                <a
                  href={selected.url}
                  target="_blank"
                  rel="noreferrer"
                  className={`mt-1 inline-flex items-center gap-1 text-sm font-semibold ${t.fixLink}`}
                >
                  Preview live file
                  <ExternalLink className="h-3.5 w-3.5" />
                </a>
              </div>
              <div className="flex flex-wrap gap-2">
                <button type="button" onClick={resetToAuto} className={t.btnGhost}>
                  <RotateCcw className="h-4 w-4" />
                  Reset to auto
                </button>
                <button type="button" onClick={save} disabled={saving} className={t.btnPrimary}>
                  <Save className="h-4 w-4" />
                  {saving ? 'Saving…' : 'Save file'}
                </button>
              </div>
            </div>

            <label className={t.checkbox}>
              <input type="checkbox" checked={useCustom} onChange={(e) => setUseCustom(e.target.checked)} />
              Use custom content (otherwise auto-generated live file is served)
            </label>

            <textarea
              value={draftContent}
              onChange={(e) => setDraftContent(e.target.value)}
              rows={compact ? 16 : 22}
              spellCheck={false}
              className={t.codeEditor}
            />

            {!useCustom ? (
              <p className={t.hint}>
                Auto mode is active. The textarea shows the current generated content for reference. Saving will keep serving the auto-generated version until custom mode is enabled.
              </p>
            ) : null}
          </div>
        ) : null}
      </div>
    </section>
  );
}
