-- Admin-managed FAQs for app (Android/iOS) and website — General, Service-based, RSA
CREATE TABLE IF NOT EXISTS public.public_faqs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  faq_group VARCHAR(20) NOT NULL CHECK (faq_group IN ('GENERAL', 'SERVICE', 'RSA')),
  section_key VARCHAR(80) NOT NULL DEFAULT 'general',
  section_title VARCHAR(120) NOT NULL DEFAULT 'General',
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  visible_app BOOLEAN NOT NULL DEFAULT TRUE,
  visible_web BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_public_faqs_group_section_order
  ON public.public_faqs (faq_group, section_key, display_order, created_at);

COMMENT ON TABLE public.public_faqs IS 'Unified FAQs for home, service pages, RSA screen, website /faq, and RSA landing';

INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'What is My FNG?', 'My FNG - Friendly Neighbourhood Garage is a network of over 100+ A Grade Multi-brand Car Servicing and Repair Stations across Mumbai, Navi Mumbai, Thane, Palghar, Nashik and Pune. We connect car owners to A-grade service centers to ensure hassle-free and high-quality maintenance experiences.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='What is My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'What brands of cars do you service at My FNG?', 'My FNG services all major car brands. Our skilled technicians are trained to handle a wide range of vehicle makes and models ensuring comprehensive care for your car.', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='What brands of cars do you service at My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'How can I find a My FNG service center near me?', 'You can find the nearest My FNG service center by visiting our website www.myfng.in/workshop-locator or by calling our customer support for assistance.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='How can I find a My FNG service center near me?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'What services does My FNG Offer?', 'My FNG offers a wide range of car services including routine maintenance, oil changes, brake repairs, engine diagnostics, tyre services and complex repairs. Our service centers are equipped to handle all your car servicing needs.', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='What services does My FNG Offer?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'How can I book a service appointment with My FNG?', 'You can book service via MyFNG AI Booking Agent - https://myfng.in/ai-booking or online through our website www.myfng.in/book-service or by calling our customer support. We offer flexible scheduling to accommodate your convenience.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='How can I book a service appointment with My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'Do you use genuine parts for repairs and servicing?', 'Yes, My FNG uses only genuine and high-quality (OEM/OES) spare parts for all repairs and servicing. We prioritize the longevity and performance of your vehicle.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='Do you use genuine parts for repairs and servicing?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'Can I get an estimate before the service is performed?', 'Yes, My FNG provides detailed estimates before any service or repair work is performed. This ensures transparency and allows you to make informed decisions about your car.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='Can I get an estimate before the service is performed?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'Is there a Warranty On The Services Provided?', 'Yes, we offer a 1000 Kms or 1 Month Warranty on the parts and labour involved in your car''s service. Warranty details are also available on our website www.myfng.in.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='Is there a Warranty On The Services Provided?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'How Can I Contact You For More Questions?', 'If you have any additional questions or need assistance you can reach out to us via our website www.myfng.in/contact-us or call us at +91-9152307030. Our customer support team is here to help.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='How Can I Contact You For More Questions?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'What Payment Options Are Available For Car Services?', 'We accept various payment methods including credit/debit cards, UPI and cash. For any specific questions about payment feel free to ask when booking your service or call us at +91-9152307030.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='What Payment Options Are Available For Car Services?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'Can Periodic Car Service Improve My Car''s Fuel Efficiency?', 'Yes, regular servicing can enhance your car''s fuel efficiency by ensuring all systems are functioning optimally. This includes replacing filters, maintaining proper tire pressure and keeping the engine well-tuned.', 11, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='Can Periodic Car Service Improve My Car''s Fuel Efficiency?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'How Long Will The Car Service Take?', 'The time required for a periodic service depends on the work needed and your car''s condition. On average a standard service may take between 5 to 6 hours. We will provide you with an estimated time during the booking process.', 12, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='How Long Will The Car Service Take?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'What Should I Do If I Notice Any Issues Between Services?', 'If you notice any unusual sounds, vibrations or dashboard warning lights contact us immediately for a diagnostic check. Addressing problems early can prevent more significant repairs.', 13, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='What Should I Do If I Notice Any Issues Between Services?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'Why Should I Keep Records Of My Car''s Services?', 'Keeping records of your car''s service history is important for warranty compliance, resale value and tracking any recurring issues. It also helps you stay informed about your car''s maintenance needs.', 14, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='Why Should I Keep Records Of My Car''s Services?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'How Often Should I Service My Car?', 'It''s generally recommended to service your car every 10,000 kilometers or every 6 months, whichever comes first. This ensures your car remains in optimal condition.', 15, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='How Often Should I Service My Car?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'Why Is Periodic Service Necessary For Every Car?', 'Periodic car service is essential to maintain your car''s safety, performance and longevity. Regular servicing helps identify problems early, preventing costly repairs and keeping your car in its best condition.', 16, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='Why Is Periodic Service Necessary For Every Car?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'GENERAL', 'general', 'General Car Service', 'How Is My FNG Periodic Car Service Better Compared To Other Car Services?', 'At My FNG we focus on delivering high-quality car services using genuine spare parts and company-recommended oils & filters to ensure your car performs at its best. We offer a 1000 Kms or 1 Month Warranty on our services ensuring peace of mind. Our expert technicians use advanced diagnostic tools and we provide transparent pricing with spare parts charged at actual cost. Additionally, our convenient online booking system and customer support set us apart from the competition.', 17, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='GENERAL' AND f.section_key='general' AND f.question='How Is My FNG Periodic Car Service Better Compared To Other Car Services?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'Why is regular periodic car service important?', 'Regular periodic car service helps maintain your car''s performance, safety, fuel efficiency, and reliability. It prevents major breakdowns by identifying minor issues early and ensures smoother driving and longer engine life.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='Why is regular periodic car service important?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'How often should I get my car serviced?', 'It is recommended to service your car every 10,000 kms or 6 months, whichever comes first. Regular servicing helps maintain optimal performance and avoids expensive repairs in the future.', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='How often should I get my car serviced?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'Do you provide free pickup and drop for car service?', 'Yes. My FNG offers convenient free pickup and drop service for most car services depending on location and service type.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='Do you provide free pickup and drop for car service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'What does a typical Periodic Car Service at My FNG include?', 'Periodic service at My FNG includes engine oil replacement, oil filter change, fluid top-ups, brake inspection, tyre pressure check, air filter cleaning, interior vacuuming, wheel rotation, and overall car health inspection.', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='What does a typical Periodic Car Service at My FNG include?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'What are the signs that my car needs periodic servicing?', 'Common signs include reduced mileage, unusual engine noise, warning lights on the dashboard, vibration while driving, poor braking performance, or delayed pickup.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='What are the signs that my car needs periodic servicing?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'How is My FNG''s Periodic Car Service different from other car garages?', 'My FNG provides trained technicians, genuine spare parts, upfront pricing, free pickup & drop, live service updates on WhatsApp, and 1,000 Kms / 1 Month service warranty for complete peace of mind.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='How is My FNG''s Periodic Car Service different from other car garages?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'Will periodic service improve my car''s mileage and performance?', 'Yes. Regular service ensures clean engine components, proper lubrication, and optimized fuel combustion, which improves mileage, pickup, and overall driving performance.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='Will periodic service improve my car''s mileage and performance?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'How long does a periodic car service take at My FNG?', 'Most periodic services are completed within the same day, depending on the car condition and additional repairs required.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='How long does a periodic car service take at My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'Will I be charged extra for spare parts during periodic service?', 'Periodic service package includes labor and listed consumables. Any additional spare parts required will be charged at actual cost after customer approval.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='Will I be charged extra for spare parts during periodic service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'What if my car needs additional repairs during service?', 'My FNG technicians will first inspect the issue, share photos/videos, provide an estimate, and proceed only after your approval.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='What if my car needs additional repairs during service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'Is there any warranty on periodic car service at My FNG?', 'Yes. My FNG provides 1,000 Kms or 1 Month service warranty on periodic car service.', 11, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='Is there any warranty on periodic car service at My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'periodic-car-service', 'Periodic Car Service', 'How can I book Periodic Car Service with My FNG?', 'You can easily book online at www.myfng.in/book-service or call customer support to schedule free pickup & drop for your car service.', 12, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='periodic-car-service' AND f.question='How can I book Periodic Car Service with My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'Why is regular car AC service important?', 'Regular AC service keeps your car''s air conditioning system working efficiently, providing proper cooling and improved air quality. It helps prevent refrigerant leaks, maintains system efficiency, and prevents costly repairs by addressing issues early.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='Why is regular car AC service important?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'How often should I service my car''s AC?', 'It''s recommended to service your car''s AC every 12 months or before the summer season to ensure proper cooling. Regular servicing also helps maintain your AC system''s performance and longevity.', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='How often should I service my car''s AC?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'What does a typical car AC service at My FNG include?', 'A typical AC service includes gas charging, refrigerant level check, leak detection, vacuuming, pressure testing, and performance inspection.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='What does a typical car AC service at My FNG include?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'Do you provide free pickup and drop for car service?', 'Yes. My FNG offers convenient free pickup and drop service for most car services depending on location and service type.', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='Do you provide free pickup and drop for car service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'What are the signs that my car''s AC needs servicing?', 'Common signs include reduced cooling performance, unusual odors, strange noises, warm air from vents, or water leakage.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='What are the signs that my car''s AC needs servicing?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'How is My FNG''s car AC service different from other service providers?', 'My FNG AC service uses genuine spare parts and company-recommended refrigerants. We also provide a 1,000 kms / 1 month service warranty for added peace of mind.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='How is My FNG''s car AC service different from other service providers?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'What is car AC gas charging and why is it necessary?', 'Car AC gas charging involves refilling refrigerant in the AC system to maintain proper cooling performance and prevent damage to AC components.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='What is car AC gas charging and why is it necessary?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'How do you detect leaks in the car AC system?', 'Specialized leak detection tools inspect refrigerant lines and components.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='How do you detect leaks in the car AC system?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'How long does a car AC service take at My FNG?', 'Service time varies with condition and complexity.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='How long does a car AC service take at My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'Will I be charged for spare parts during AC service?', 'Yes, spare parts are charged at actual cost.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='Will I be charged for spare parts during AC service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'What happens if my AC system needs repairs beyond a standard service?', 'Technicians will recommend the required repairs and share an estimate before proceeding.', 11, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='What happens if my AC system needs repairs beyond a standard service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'What should I do if my car''s AC is still not cooling properly after service?', 'Contact My FNG under the warranty for inspection and resolution.', 12, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='What should I do if my car''s AC is still not cooling properly after service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'ac-service', 'AC Service', 'How can I schedule an AC service with My FNG?', 'Online booking via website www.myfng.in/book-service or by calling directly.', 13, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='ac-service' AND f.question='How can I schedule an AC service with My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'Why is car engine service important for my car?', 'Regular engine service keeps your car performing efficiently, enhances fuel economy, and prevents major repairs.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='Why is car engine service important for my car?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'How often should I get my car''s engine serviced?', 'Recommended every 6 months or 10,000 km (refer to manufacturer''s recommendations).', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='How often should I get my car''s engine serviced?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'Do you provide free pickup and drop for car service?', 'Yes. My FNG offers convenient free pickup and drop service for most car services depending on location and service type.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='Do you provide free pickup and drop for car service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'What does an engine service at My FNG include?', 'Engine service includes engine bay inspection, engine tuning, wiring inspection, belt and hose inspection, spark plug cleaning, air filter cleaning, and throttle body cleaning.', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='What does an engine service at My FNG include?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'What are the signs that my car''s engine needs servicing?', 'Warning lights, rough idling, unusual engine noise, smoke from the exhaust, or reduced fuel economy.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='What are the signs that my car''s engine needs servicing?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'How is My FNG engine service different from others?', 'Use of genuine parts plus 1,000 Kms/1 Month Warranty and thorough diagnostics.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='How is My FNG engine service different from others?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'Will I be charged for spare parts during engine service?', 'Yes, parts are billed at actual cost.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='Will I be charged for spare parts during engine service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'How long does an engine service take?', 'Time depends on diagnostics and vehicle condition.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='How long does an engine service take?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'What should I do if I notice engine issues between services?', 'Contact support for diagnostics to prevent serious problems.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='What should I do if I notice engine issues between services?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'Do you offer any warranty on engine service?', 'Yes, 1,000 Kms/1 Month Warranty covers engine services.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='Do you offer any warranty on engine service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'How can I increase the lifespan of my car''s engine?', 'Regular maintenance, timely oil changes, and proper driving habits help increase engine life.', 11, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='How can I increase the lifespan of my car''s engine?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-engine-service', 'Car Engine Service', 'How can I book an Engine service with My FNG?', 'Online booking via website www.myfng.in/book-service or by calling directly.', 12, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-engine-service' AND f.question='How can I book an Engine service with My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'Why is regular car battery service important?', 'Regular battery service ensures reliable starting, prevents sudden breakdowns, and extends battery life.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='Why is regular car battery service important?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'How often should my car battery be checked?', 'Battery health should be checked every 6 months or before extreme summer and monsoon seasons.', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='How often should my car battery be checked?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'Do you provide free pickup and drop for car service?', 'Yes. My FNG offers convenient free pickup and drop service for most car services depending on location and service type.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='Do you provide free pickup and drop for car service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'What does a battery service at My FNG include?', 'Battery inspection, voltage testing, terminal cleaning, charging, and jump-start support if required.', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='What does a battery service at My FNG include?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'How do I know if my car battery is weak?', 'Slow engine cranking, dim headlights, warning lights, or frequent jump-starts indicate a weak battery.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='How do I know if my car battery is weak?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'How long does a car battery usually last?', 'Most car batteries last between 2 to 3 years, depending on usage and weather conditions.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='How long does a car battery usually last?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'Can extreme weather affect my car battery?', 'Yes. High heat and extreme cold can reduce battery efficiency and lifespan.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='Can extreme weather affect my car battery?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'Do you replace car batteries at My FNG?', 'Yes. Battery replacement is available using genuine, manufacturer-approved batteries.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='Do you replace car batteries at My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'Will battery replacement cost extra?', 'Yes. The cost of the new battery is charged at actual market price.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='Will battery replacement cost extra?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'How long does battery service take?', 'Battery inspection and service usually take 30 to 60 minutes.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='How long does battery service take?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'Is battery service covered under warranty?', 'Battery service labor is covered under My FNG warranty, while battery warranty depends on the manufacturer.', 11, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='Is battery service covered under warranty?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'battery-service', 'Battery Service', 'How can I schedule a Battery service with My FNG?', 'Online booking via website www.myfng.in/book-service or by calling directly.', 12, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='battery-service' AND f.question='How can I schedule a Battery service with My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'Why is regular brake service necessary?', 'Brake service ensures safe stopping performance and prevents brake failure.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='Why is regular brake service necessary?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'How often should brakes be inspected?', 'Brakes should be checked every 10,000 km or every 6 months.', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='How often should brakes be inspected?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'Do you provide free pickup and drop for car service?', 'Yes. My FNG offers convenient free pickup and drop service for most car services depending on location and service type.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='Do you provide free pickup and drop for car service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'What does brake service at My FNG include?', 'Brake pad inspection, cleaning, greasing, brake fluid check, and system diagnostics.', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='What does brake service at My FNG include?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'What are the signs that my brakes need servicing?', 'Squealing noise, grinding sound, vibration, soft brake pedal, or warning lights.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='What are the signs that my brakes need servicing?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'How long do brake pads usually last?', 'Brake pads typically last between 15,000–40,000 km, depending on driving habits.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='How long do brake pads usually last?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'Do you replace brake pads and discs?', 'Yes. Brake pad and disc replacement is done using genuine or OEM-approved parts.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='Do you replace brake pads and discs?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'Is brake fluid replacement included?', 'Brake fluid replacement is recommended every 2 years and charged separately if required.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='Is brake fluid replacement included?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'How long does brake service take?', 'Standard brake service usually takes 1 to 2 hours.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='How long does brake service take?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'Can worn brakes affect fuel efficiency?', 'Yes. Dragging or worn brakes can increase fuel consumption.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='Can worn brakes affect fuel efficiency?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'Is there a warranty on brake service?', 'Yes. Brake service comes with a 1,000 km or 1 month service warranty.', 11, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='Is there a warranty on brake service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'brake-service', 'Brake Service', 'How can I book a Brake service with My FNG?', 'Online booking via website www.myfng.in/book-service or by calling directly.', 12, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='brake-service' AND f.question='How can I book a Brake service with My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'Why is tyre maintenance important?', 'Proper tyre maintenance ensures safety, better handling, and improved fuel efficiency.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='Why is tyre maintenance important?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'What does tyre service at My FNG include?', 'Tyre pressure check, rotation, balancing, alignment inspection, and condition check.', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='What does tyre service at My FNG include?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'Do you provide free pickup and drop for car service?', 'Yes. My FNG offers convenient free pickup and drop service for most car services depending on location and service type.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='Do you provide free pickup and drop for car service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'How often should tyre rotation be done?', 'Tyre rotation is recommended every 10,000 km or 6 months.', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='How often should tyre rotation be done?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'What are signs that tyres need replacement?', 'Low tread depth, uneven wear, cracks, bulges, or frequent punctures.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='What are signs that tyres need replacement?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'What is the minimum safe tyre tread depth?', 'The recommended minimum tread depth is 1.5 mm.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='What is the minimum safe tyre tread depth?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'What is tyre balancing and why is it needed for smooth driving?', 'Tyre balancing prevents vibrations and ensures even tyre wear.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='What is tyre balancing and why is it needed for smooth driving?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'What is wheel alignment and why is it important for my car?', 'Wheel alignment ensures correct wheel angles for stable steering and tyre longevity.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='What is wheel alignment and why is it important for my car?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'Can improper tyres affect braking?', 'Yes. Worn or improperly inflated tyres reduce braking efficiency.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='Can improper tyres affect braking?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'How long does tyre service take?', 'Basic tyre service takes around 30 to 60 minutes.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='How long does tyre service take?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'Do you offer tyre replacement?', 'Yes. Tyre replacement is available with genuine and branded tyre options.', 11, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='Do you offer tyre replacement?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'tyre-service', 'Tyre Service', 'How can I book Wheel Alignment & Balancing with My FNG?', 'Online booking via website www.myfng.in/book-service or by calling directly.', 12, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='tyre-service' AND f.question='How can I book Wheel Alignment & Balancing with My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'What is included in denting and painting service?', 'Dent removal, surface preparation, primer, paint application, clear coat, and polishing.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='What is included in denting and painting service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'How long does denting and painting take?', 'The process usually takes 2 to 5 days depending on damage severity.', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='How long does denting and painting take?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'Do you provide free pickup and drop for car service?', 'Yes. My FNG offers convenient free pickup and drop service for most car services depending on location and service type.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='Do you provide free pickup and drop for car service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'Can you match my car''s original paint color?', 'Yes. We use computerized color matching for accurate paint finish.', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='Can you match my car''s original paint color?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'Is denting and painting covered under insurance?', 'Yes. Insurance claim support is available where applicable.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='Is denting and painting covered under insurance?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'Does denting & painting cover rusted panels?', 'Rust treatment may require additional work and is not included in standard packages.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='Does denting & painting cover rusted panels?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'Will the paint quality last long?', 'Yes. High-quality paints and clear coats are used for long-lasting finish.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='Will the paint quality last long?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'Do you provide warranty on paint work?', 'Yes. Paint and workmanship warranty is provided.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='Do you provide warranty on paint work?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'Can minor scratches be fixed without full repainting?', 'Yes. Minor scratches can be corrected through rubbing and polishing.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='Can minor scratches be fixed without full repainting?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'Is part removal included in denting service?', 'Yes, if required for quality repair and finish.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='Is part removal included in denting service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'Can I service multiple panels together?', 'Yes. Multiple-panel denting and painting packages are available.', 11, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='Can I service multiple panels together?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'denting-painting', 'Denting & Painting', 'How can I schedule a Denting & Painting service with My FNG?', 'Online booking via website www.myfng.in/book-service or by calling directly.', 12, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='denting-painting' AND f.question='How can I schedule a Denting & Painting service with My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'What is car detailing?', 'Car detailing is a deep cleaning and protection process for both interior and exterior surfaces.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='What is car detailing?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'What does exterior detailing include?', 'Washing, claying, polishing, waxing, and paint protection treatment.', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='What does exterior detailing include?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'Do you provide free pickup and drop for car service?', 'Yes. My FNG offers convenient free pickup and drop service for most car services depending on location and service type.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='Do you provide free pickup and drop for car service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'What does interior detailing include?', 'Interior vacuuming, seat shampooing, dashboard cleaning, and odor removal.', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='What does interior detailing include?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'How often should car detailing be done?', 'Car detailing is recommended every 6 months.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='How often should car detailing be done?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'What is ceramic or nano coating?', 'It is a protective layer applied on paint to enhance shine and protect from scratches and UV rays.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='What is ceramic or nano coating?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'How long does detailing service take?', 'Depending on package, detailing can take 4 to 8 hours.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='How long does detailing service take?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'Is detailing safe for old cars?', 'Yes. Detailing improves appearance and preserves interior and exterior surfaces.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='Is detailing safe for old cars?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'Does detailing remove scratches?', 'Minor scratches and swirl marks can be reduced through polishing.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='Does detailing remove scratches?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'Will detailing improve resale value?', 'Yes. A well-maintained car has higher resale value.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='Will detailing improve resale value?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'Is detailing covered under warranty?', 'Detailing quality assurance is provided for the service performed.', 11, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='Is detailing covered under warranty?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'car-detailing', 'Car Detailing', 'How can I book a Detailing service with My FNG?', 'Online booking via website www.myfng.in/book-service or by calling directly.', 12, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='car-detailing' AND f.question='How can I book a Detailing service with My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'Why is clutch maintenance important?', 'Proper clutch maintenance ensures smooth gear shifting and prevents breakdowns.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='Why is clutch maintenance important?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'What are signs of clutch problems?', 'Hard gear shifting, clutch slipping, burning smell, or unusual noise.', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='What are signs of clutch problems?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'Do you provide free pickup and drop for car service?', 'Yes. My FNG offers convenient free pickup and drop service for most car services depending on location and service type.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='Do you provide free pickup and drop for car service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'What does clutch maintenance include?', 'Clutch inspection, adjustment, pressure plate check, and replacement if required.', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='What does clutch maintenance include?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'How long does a clutch usually last?', 'A clutch can last between 50,000 to 80,000 km depending on driving habits.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='How long does a clutch usually last?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'How long does clutch service take?', 'Clutch maintenance or replacement usually takes 6 to 8 hours.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='How long does clutch service take?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'Do you use genuine clutch parts?', 'Yes. Only manufacturer-approved or OEM-quality clutch parts are used.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='Do you use genuine clutch parts?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'Is clutch replacement included in maintenance package?', 'Replacement parts are charged separately at actual cost.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='Is clutch replacement included in maintenance package?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'Can poor clutch affect fuel efficiency?', 'Yes. A slipping clutch increases fuel consumption.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='Can poor clutch affect fuel efficiency?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'Is there a warranty on clutch service?', 'Labor warranty is provided; parts carry manufacturer warranty.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='Is there a warranty on clutch service?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'How can I increase clutch life?', 'Avoid riding the clutch, use proper gear shifting, and follow regular inspections.', 11, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='How can I increase clutch life?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'SERVICE', 'clutch-maintenance', 'Clutch Maintenance', 'How can I schedule a Clutch Service with My FNG?', 'Online booking via website www.myfng.in/book-service or by calling directly.', 12, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='SERVICE' AND f.section_key='clutch-maintenance' AND f.question='How can I schedule a Clutch Service with My FNG?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'RSA', 'rsa', 'RSA', 'How fast is RSA?', 'Our average response time is 30-45 minutes depending on your location.', 1, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='RSA' AND f.question='How fast is RSA?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'RSA', 'rsa', 'RSA', 'Is RSA available 24/7?', 'Yes, our emergency team is available round the clock.', 2, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='RSA' AND f.question='Is RSA available 24/7?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'RSA', 'rsa', 'RSA', 'What if my car cannot be fixed on spot?', 'We provide towing services to the nearest MyFNG certified workshop.', 3, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='RSA' AND f.question='What if my car cannot be fixed on spot?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'RSA', 'rsa', 'RSA', 'Does RSA cover fuel delivery?', 'Yes, we provide emergency fuel delivery (fuel cost extra).', 4, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='RSA' AND f.question='Does RSA cover fuel delivery?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'RSA', 'rsa', 'RSA', 'Is jumpstart safe for my car?', 'Yes, our technicians use professional equipment safe for modern car electronics.', 5, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='RSA' AND f.question='Is jumpstart safe for my car?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'RSA', 'rsa', 'RSA', 'What areas do you cover?', 'We currently cover all major cities and highways across India.', 6, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='RSA' AND f.question='What areas do you cover?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'RSA', 'rsa', 'RSA', 'How much does RSA cost?', 'Pricing varies by service type and location. Towing starts at ₹25/km.', 7, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='RSA' AND f.question='How much does RSA cost?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'RSA', 'rsa', 'RSA', 'Can I track the RSA vehicle?', 'Yes, once dispatched you receive real-time tracking of the assistance vehicle.', 8, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='RSA' AND f.question='Can I track the RSA vehicle?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'RSA', 'rsa', 'RSA', 'Do I need a membership for RSA?', 'No membership required. However, MyFNG Pro and Max members get priority dispatch and discounted rates.', 9, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='RSA' AND f.question='Do I need a membership for RSA?');
INSERT INTO public.public_faqs (faq_group, section_key, section_title, question, answer, display_order, active, visible_app, visible_web) SELECT 'RSA', 'rsa', 'RSA', 'What happens after towing?', 'Your car is towed to the nearest MyFNG partner workshop where a full inspection is done and you receive a detailed estimate.', 10, TRUE, TRUE, TRUE WHERE NOT EXISTS (SELECT 1 FROM public.public_faqs f WHERE f.faq_group='RSA' AND f.question='What happens after towing?');
