-- ============================================
-- RUN ALL: Post Job Completion Workflow SQL Pack
-- Generated by Cursor agent
--
-- IMPORTANT:
-- - This file contains enum ALTERs (lead_status). Many Postgres runners wrap scripts in a transaction,
--   and ALTER TYPE ... ADD VALUE will fail inside a transaction in some setups.
-- - If your runner auto-wraps in a transaction, run the enum section first using a non-transactional runner.
-- ============================================

-- ============================================
-- A) lead_status enum values (doc-aligned)
-- ============================================
-- Core post-job statuses
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'WORK_COMPLETED';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'QC_PENDING';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'QC_APPROVED';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'READY_FOR_BILLING';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'INVOICE_GENERATED';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'AWAITING_PAYMENT';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'PARTIAL_PAYMENT';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'COD_PENDING';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'READY_FOR_DELIVERY';

-- Misc statuses used in existing app flows
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'VEHICLE_DROPPED_AT_WORKSHOP';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'MECHANIC_WORKING';

ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'REWORK_REQUIRED';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'DELIVERED_TO_CUSTOMER';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'COMPLAINT_OPENED';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'CUSTOMER_UNHAPPY';
ALTER TYPE lead_status ADD VALUE IF NOT EXISTS 'COMPLETED';

-- ============================================
-- B) QC trigger alignment (FAILED -> REWORK_REQUIRED, PASSED -> READY_FOR_BILLING)
-- ============================================
CREATE OR REPLACE FUNCTION update_lead_qc_status()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.qc_status IS DISTINCT FROM OLD.qc_status THEN
    UPDATE public.service_leads
    SET
      qc_status = NEW.qc_status,
      qc_performed_by = NEW.supervisor_id,
      qc_performed_at = NOW(),
      qc_notes = NEW.supervisor_notes,
      updated_at = NOW()
    WHERE id = NEW.lead_id;

    IF NEW.qc_status = 'PASSED' THEN
      UPDATE public.service_leads
      SET
        status = 'READY_FOR_BILLING',
        updated_at = NOW()
      WHERE id = NEW.lead_id
        AND status IN ('WORK_COMPLETED', 'QC_PENDING');
    END IF;

    IF NEW.qc_status = 'FAILED' THEN
      UPDATE public.service_leads
      SET
        status = 'REWORK_REQUIRED',
        updated_at = NOW()
      WHERE id = NEW.lead_id
        AND status IN ('WORK_COMPLETED', 'QC_PENDING');
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- C) Core workflow columns (read_only / archive / CSE follow-up)
-- ============================================
ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS read_only BOOLEAN DEFAULT false;
ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS archived_by UUID REFERENCES users_login(id);
ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS retention_period_years INTEGER DEFAULT 7;

ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS csat_rating INTEGER CHECK (csat_rating >= 1 AND csat_rating <= 5);
ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS csat_feedback TEXT;
ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS cse_followup_due BOOLEAN DEFAULT false;
ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS cse_followup_due_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS cse_followup_completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS cse_followup_by UUID REFERENCES users_login(id);
ALTER TABLE service_leads ADD COLUMN IF NOT EXISTS cse_notes TEXT;

CREATE INDEX IF NOT EXISTS idx_service_leads_archived ON service_leads(archived_at) WHERE archived_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_service_leads_cse_followup_due ON service_leads(cse_followup_due, cse_followup_due_at) WHERE cse_followup_due = true;

-- ============================================
-- D) Invoice document storage + billing checklist snapshot
-- ============================================
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS read_only BOOLEAN DEFAULT false;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS archived_by UUID REFERENCES users_login(id);

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS document_url TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS document_type VARCHAR(20) DEFAULT 'HTML';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS document_generated_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE invoice_reviews ADD COLUMN IF NOT EXISTS checklist_data JSONB;
ALTER TABLE invoice_reviews ADD COLUMN IF NOT EXISTS review_stage VARCHAR(50);

-- ============================================
-- E) CSE follow-up trigger (DELIVERED_TO_CUSTOMER)
-- ============================================
CREATE OR REPLACE FUNCTION set_cse_followup_due()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'DELIVERED_TO_CUSTOMER' AND OLD.status IS DISTINCT FROM 'DELIVERED_TO_CUSTOMER' THEN
    NEW.cse_followup_due := true;
    NEW.cse_followup_due_at := NOW() + INTERVAL '24 hours';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_set_cse_followup_due ON service_leads;
CREATE TRIGGER trigger_set_cse_followup_due
  BEFORE UPDATE ON service_leads
  FOR EACH ROW
  EXECUTE FUNCTION set_cse_followup_due();

-- ============================================
-- F) DB-level read_only enforcement (recommended in doc; implemented here)
-- ============================================
CREATE OR REPLACE FUNCTION prevent_updates_when_read_only()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.read_only = true THEN
    RAISE EXCEPTION 'Lead is read-only (archived/locked). Updates are not permitted.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_prevent_updates_when_read_only ON service_leads;
CREATE TRIGGER trigger_prevent_updates_when_read_only
  BEFORE UPDATE ON service_leads
  FOR EACH ROW
  WHEN (OLD.read_only IS TRUE)
  EXECUTE FUNCTION prevent_updates_when_read_only();

CREATE OR REPLACE FUNCTION prevent_invoice_updates_when_read_only()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.read_only = true THEN
    RAISE EXCEPTION 'Invoice is read-only (archived/locked). Updates are not permitted.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_prevent_invoice_updates_when_read_only ON invoices;
CREATE TRIGGER trigger_prevent_invoice_updates_when_read_only
  BEFORE UPDATE ON invoices
  FOR EACH ROW
  WHEN (OLD.read_only IS TRUE)
  EXECUTE FUNCTION prevent_invoice_updates_when_read_only();

-- ============================================
-- G) In-app notifications schema (no external SMS/WhatsApp required)
-- ============================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_type') THEN
    CREATE TYPE notification_type AS ENUM (
      'LEAD_ASSIGNED',
      'LEAD_ACCEPTED',
      'LEAD_REJECTED',
      'TEAM_ASSIGNED',
      'JOB_STARTED',
      'JOB_COMPLETED',
      'EXTRA_WORK_REQUESTED',
      'EXTRA_WORK_APPROVED',
      'EXTRA_WORK_REJECTED',
      'QC_APPROVED',
      'QC_REJECTED',
      'PICKUP_SCHEDULED',
      'PICKUP_STARTED',
      'PICKUP_COMPLETED',
      'OTP_VERIFIED',
      'INVOICE_GENERATED',
      'INVOICE_SENT',
      'PAYMENT_RECEIVED',
      'FOLLOW_UP_SCHEDULED',
      'LEAD_CLOSED',
      'SLA_WARNING',
      'SLA_BREACH'
    );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_priority') THEN
    CREATE TYPE notification_priority AS ENUM ('LOW','MEDIUM','HIGH','URGENT');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users_login(id) ON DELETE CASCADE,
  type notification_type NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  priority notification_priority DEFAULT 'MEDIUM',
  lead_id UUID REFERENCES service_leads(id) ON DELETE SET NULL,
  lead_number VARCHAR(50),
  related_user_id UUID,
  related_user_name VARCHAR(255),
  action_url TEXT,
  metadata JSONB,
  is_read BOOLEAN DEFAULT FALSE,
  read_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_lead_id ON notifications(lead_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id, is_read) WHERE is_read = FALSE;


