-- Add missing columns to workshops table for enhanced workshop profile
ALTER TABLE public.workshops
ADD COLUMN IF NOT EXISTS map_link text,
ADD COLUMN IF NOT EXISTS gst_number varchar(20),
ADD COLUMN IF NOT EXISTS district varchar(100),
ADD COLUMN IF NOT EXISTS rto_code varchar(20),
ADD COLUMN IF NOT EXISTS mapping_pincodes jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS pickup_drop_km numeric,
ADD COLUMN IF NOT EXISTS one_day_capacity integer,
ADD COLUMN IF NOT EXISTS latitude numeric,
ADD COLUMN IF NOT EXISTS longitude numeric,
ADD COLUMN IF NOT EXISTS working_time varchar(50),
ADD COLUMN IF NOT EXISTS working_days jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS google_place_id text,
ADD COLUMN IF NOT EXISTS photos jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS workshop_type varchar(50),
ADD COLUMN IF NOT EXISTS designation varchar(100),
ADD COLUMN IF NOT EXISTS is_whatsapp boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS alt_mobile varchar(20),
ADD COLUMN IF NOT EXISTS id_proof text,
ADD COLUMN IF NOT EXISTS bank_name varchar(100),
ADD COLUMN IF NOT EXISTS account_number varchar(50),
ADD COLUMN IF NOT EXISTS ifsc_code varchar(20),
ADD COLUMN IF NOT EXISTS upi_id varchar(50);