-- ================================================
-- UPDATE CAR MODELS TABLE WITH NEW DATA
-- ================================================
-- This script will:
-- 1. Delete all existing car models
-- 2. Add new car models with class instead of variant
-- ================================================

-- Step 1: Delete all existing car models
DELETE FROM car_models;

-- Step 2: Insert new car models (variant = NULL, added class column concept)
-- Note: Using model_name for class since variant column exists in schema

INSERT INTO car_models (make, model_name, variant, is_active) VALUES
('HYUNDAI', 'ACCENT', 'SEDANS', true),
('HONDA', 'ACCORD', 'PREMIUM LUXURY', true),
('HYUNDAI', 'ALCAZAR', 'SUV/MUVs', true),
('MARUTI', 'ALTO', 'HATCHBACK', true),
('TATA', 'ALTROZ', 'PREMIUM HATCHBACK', true),
('MAHINDRA', 'ALTURAS', 'SUV/MUVs', true),
('HONDA', 'AMAZE', 'SEDANS', true),
('CHEVROLET', 'AMEO', 'SEDANS', true),
('TATA', 'ARIA', 'SUV/MUVs', true),
('FORD', 'ASPIRE', 'SEDANS', true),
('HYUNDAI', 'AURA', 'SEDANS', true),
('CHEVROLET', 'AVEO', 'SEDANS', true),
('MARUTI', 'BALENO', 'PREMIUM HATCHBACK', true),
('CHEVROLET', 'BEAT', 'HATCHBACK', true),
('MAHINDRA', 'BOLERO', 'SUV/MUVs', true),
('TATA', 'BOLT', 'HATCHBACK', true),
('HONDA', 'BRIO', 'HATCHBACK', true),
('HONDA', 'BRV', 'SEDANS', true),
('TOYOTA', 'CAMRY', 'PREMIUM LUXURY', true),
('MARUTI', 'CELERIO', 'HATCHBACK', true),
('MARUTI', 'CIAZ', 'SEDANS', true),
('HONDA', 'CITY', 'SEDANS', true),
('HONDA', 'CIVIC', 'SEDANS', true),
('TOYOTA', 'COROLLA', 'SEDANS', true),
('HYUNDAI', 'EXTER', 'PREMIUM HATCHBACK', true),
('HYUNDAI', 'CRETA', 'SUV/MUVs', true),
('CHEVROLET', 'CRUZE', 'PREMIUM SUV/MUVs', true),
('TOYOTA', 'CRYSTA', 'SUV/MUVs', true),
('NISSAN', 'DATSUN', 'COMPACT SUV', true),
('RENAULT', 'DUSTER', 'COMPACT SUV', true),
('MARUTI', 'DZIRE', 'SEDANS', true),
('FORD', 'ECO SPORT', 'COMPACT SUV', true),
('MARUTI', 'EECO', 'SEDANS', true),
('HYUNDAI', 'ELANTRA', 'SEDANS', true),
('FORD', 'ENDEAVOUR', 'PREMIUM HATCHBACK', true),
('HYUNDAI', 'EON', 'HATCHBACK', true),
('MARUTI', 'ERTIGA', 'COMPACT SUV', true),
('MARUTI', 'ESTEEM', 'SEDANS', true),
('TOYOTA', 'ETIOS', 'SEDANS', true),
('SKODA', 'FABIA', 'PREMIUM HATCHBACK', true),
('FORD', 'FIESTA', 'PREMIUM HATCHBACK', true),
('FORD', 'FIGO', 'HATCHBACK', true),
('TOYOTA', 'FORTUNER', 'PREMIUM SUV/MUVs', true),
('FORD', 'FUSION', 'PREMIUM HATCHBACK', true),
('HYUNDAI', 'GETZ', 'HATCHBACK', true),
('TOYOTA', 'GLANZA', 'PREMIUM HATCHBACK', true),
('MG', 'GLOSTER', 'PREMIUM SUV/MUVs', true),
('HYUNDAI', 'GRAND I10', 'HATCHBACK', true),
('MARUTI', 'FRONX', 'COMPACT SUV', true),
('MARUTI', 'GRAND VITARA', 'SUV/MUVs', true),
('MARUTI', 'GYPSY', 'COMPACT SUV', true),
('MG', 'HECTOR', 'PREMIUM SUV/MUVs', true),
('TATA', 'HEXA', 'SUV/MUVs', true),
('HYUNDAI', 'I 20', 'PREMIUM HATCHBACK', true),
('MARUTI', 'IGNIS', 'PREMIUM HATCHBACK', true),
('FORD', 'IKON', 'SEDANS', true),
('TATA', 'INDICA', 'HATCHBACK', true),
('TATA', 'INDIGO', 'SEDANS', true),
('TOYOTA', 'INNOVA', 'SUV/MUVs', true),
('HONDA', 'JAZZ', 'PREMIUM HATCHBACK', true),
('VOLKSWAGEN', 'JETTA', 'PREMIUM LUXURY', true),
('NISSAN', 'KICKS', 'COMPACT SUV', true),
('RENAULT', 'KIGER', 'COMPACT SUV', true),
('SKODA', 'KODIAQ', 'PREMIUM SUV/MUVs', true),
('SKODA', 'KUSHAQ', 'PREMIUM SUV/MUVs', true),
('MAHINDRA', 'KUV 100', 'PREMIUM HATCHBACK', true),
('RENAULT', 'KWID', 'HATCHBACK', true),
('SKODA', 'LAURA', 'PREMIUM LUXURY', true),
('FCA', 'LINEA', 'PREMIUM HATCHBACK', true),
('MAHINDRA', 'LOGAN', 'SEDANS', true),
('MAHINDRA', 'MAARZZO', 'SUV/MUVs', true),
('NISSAN', 'MAGNITE', 'COMPACT SUV', true),
('TATA', 'MANZA', 'SEDANS', true),
('NISSAN', 'MICRA', 'HATCHBACK', true),
('TATA', 'NANO', 'HATCHBACK', true),
('TATA', 'NEXON', 'COMPACT SUV', true),
('SKODA', 'OCTAIVA', 'PREMIUM LUXURY', true),
('MARUTI', 'OMNI', 'SEDANS', true),
('FCA', 'PALIO', 'HATCHBACK', true),
('VOLKSWAGEN', 'PASSAT', 'PREMIUM LUXURY', true),
('VOLKSWAGEN', 'POLO', 'PREMIUM HATCHBACK', true),
('RENAULT', 'PULSE', 'HATCHBACK', true),
('TATA', 'PUNCH', 'PREMIUM HATCHBACK', true),
('FCA', 'PUNTO', 'HATCHBACK', true),
('TOYOTA', 'QUALIS', 'SUV/MUVs', true),
('MAHINDRA', 'QUANTO', 'SUV/MUVs', true),
('SKODA', 'RAPID', 'SEDANS', true),
('MARUTI', 'RITZ', 'HATCHBACK', true),
('MARUTI', 'S CROSS', 'COMPACT SUV', true),
('MARUTI', 'S PRESSO', 'HATCHBACK', true),
('TATA', 'SAFARI OLD', 'SUV/MUVs', true),
('CHEVROLET', 'SAIL', 'SEDANS', true),
('HYUNDAI', 'SANTA', 'PREMIUM SUV/MUVs', true),
('HYUNDAI', 'SANTRO', 'HATCHBACK', true),
('RENAULT', 'SCALA', 'SEDANS', true),
('MAHINDRA', 'SCORPIO', 'SUV/MUVs', true),
('KIA', 'SELTOS', 'SUV/MUVs', true),
('HYUNDAI', 'SONATA', 'PREMIUM SUV/MUVs', true),
('KIA', 'SONET', 'COMPACT SUV', true),
('CHEVROLET', 'SPARK', 'HATCHBACK', true),
('TATA', 'SUMO', 'SUV/MUVs', true),
('NISSAN', 'SUNNY', 'SEDANS', true),
('SKODA', 'SUPERB', 'PREMIUM LUXURY', true),
('MARUTI', 'SWIFT', 'HATCHBACK', true),
('MARUTI', 'SX4', 'SEDANS', true),
('CHEVROLET', 'TAVERA', 'SUV/MUVs', true),
('NISSAN', 'TERRANO', 'SUV/MUVs', true),
('MAHINDRA', 'THAR', 'SUV/MUVs', true),
('TATA', 'TIAGO', 'SEDANS', true),
('TATA', 'TIGOR', 'SEDANS', true),
('VOLKSWAGEN', 'TIGUAN', 'SUV/MUVs', true),
('MARUTI', 'TOUR', 'SEDANS', true),
('RENAULT', 'TRIBER', 'SEDANS', true),
('HYUNDAI', 'TUCSON', 'PREMIUM SUV/MUVs', true),
('MAHINDRA', 'TUV 300', 'SUV/MUVs', true),
('TOYOTA', 'URBAN CRUISER', 'COMPACT SUV', true),
('OTHERS', 'VENTO', 'SEDANS', true),
('HYUNDAI', 'VENUE', 'COMPACT SUV', true),
('MAHINDRA', 'VERITO', 'SEDANS', true),
('HYUNDAI', 'VERNA', 'SEDANS', true),
('MARUTI', 'VERSA', 'SEDANS', true),
('TATA', 'VISTA', 'SEDANS', true),
('MARUTI', 'VITARA BREZZA', 'SUV/MUVs', true),
('MARUTI', 'WAGON R', 'HATCHBACK', true),
('HONDA', 'WRV', 'PREMIUM HATCHBACK', true),
('HYUNDAI', 'XCENT', 'SEDANS', true),
('MARUTI', 'XL6', 'COMPACT SUV', true),
('MAHINDRA', 'XUV 300', 'COMPACT SUV', true),
('MAHINDRA', 'XUV 500', 'COMPACT SUV', true),
('MAHINDRA', 'XYLO', 'SUV/MUVs', true),
('TOYOTA', 'YARIS', 'SEDANS', true),
('MARUTI', 'ZEN', 'HATCHBACK', true),
('MARUTI', 'ZEN ESTILO', 'HATCHBACK', true),
('TATA', 'ZEST', 'SEDANS', true),
('KIA', 'CARENS', 'SUV/MUVs', true),
('KIA', 'CARNIVAL', 'PREMIUM SUV/MUVs', true),
('TOYOTA', 'LIVA', 'HATCHBACK', true),
('TOYOTA', 'TAISOR', 'COMPACT SUV', true),
('TOYOTA', 'RUMION', 'COMPACT SUV', true),
('TOYOTA', 'HYRYDER', 'SUV/MUVs', true),
('VOLKSWAGEN', 'VIRTUS', 'SEDANS', true),
('TATA', 'HARRIER', 'PREMIUM SUV/MUVs', true),
('CHEVROLET', 'ENJOY', 'COMPACT SUV', true),
('HONDA', 'CRV', 'SUV/MUVs', true),
('HONDA', 'MOBILIO', 'SEDANS', true),
('TATA', 'SAFARI NEW', 'PREMIUM SUV/MUVs', true),
('MAHINDRA', 'XUV 700', 'PREMIUM SUV/MUVs', true),
('SKODA', 'SALIVA', 'PREMIUM HATCHBACK', true),
('SKODA', 'SLAVIA', 'SEDANS', true),
('TOYOTA', 'ETIOS CROSS', 'PREMIUM HATCHBACK', true),
('MERCEDES', 'MERCEDES', 'PREMIUM LUXURY', true),
('JAGUAR', 'JAGUAR', 'PREMIUM LUXURY', true),
('BMW', 'BMW', 'PREMIUM LUXURY', true),
('MAHINDRA', 'NUVOSPORT', 'SUV/MUVs', true),
('MARUTI', 'A STAR', 'HATCHBACK', true),
('FORD', 'FREESTYLE', 'PREMIUM HATCHBACK', true),
('AUDI', 'AUDI', 'PREMIUM LUXURY', true),
('ISUJU', 'ISUJU D MAX', 'PREMIUM SUV/MUVs', true),
('JEEP', 'COMPASS', 'SUV/MUVs', true),
('MAHINDRA', 'GENIO', 'SUV/MUVs', true),
('RENAULT', 'LODGY', 'PREMIUM HATCHBACK', true),
('TOYOTA', 'HYCROSS', 'PREMIUM SUV/MUVs', true),
('TATA', 'SAFARI (OLD)', 'SUV/MUVs', true);

-- Verify the update
SELECT 
  COUNT(*) as total_models,
  COUNT(DISTINCT make) as total_makes
FROM car_models;

-- Show sample records
SELECT make, model_name, variant as class, is_active
FROM car_models
ORDER BY make, model_name
LIMIT 20;

