export const metadata = {
  title: 'Terms and Conditions | MyFNG',
  description: 'MyFNG Terms and Conditions',
};

const TERMS_CONTENT = `MyFNG New - Terms and Conditions Draft

CONTRACTUAL RELATIONSHIP
MyFNG Autocare Private Limited, a company duly incorporated under the Companies Act, 2013 and having its registered office at A/309, Centrum Business Square, Road No 16, Wagle Industrial Estate, Thane (W), Thane-400604, Maharashtra, India ("MyFNG" or "Company"), owns and operates a digital platform under the brand name MyFNG, which enables users to discover, schedule, and manage car maintenance, repair, inspection, and related automotive services offered by independent third-party service providers ("Partner Workshops").

These Terms and Conditions ("Terms") govern your access to and use of the MyFNG website available at www.myfng.in ("Website") and the MyFNG mobile application ("App"), including all associated features, content, functionalities, and services provided through them (collectively referred to as the "Services"). The Website and the App are together referred to as the "Platform."

These Terms create a binding legal agreement between MyFNG ("we", "us", "our") and any person who accesses or uses the Platform ("User", "you", "your"). By visiting, registering on, downloading, or using the Platform or by availing any Services, you confirm that you have carefully read, understood, and agreed to be bound by these Terms, thereby establishing a contractual relationship between you and the Company.

If you do not agree with any part of these Terms, you must not access or use the Platform or Services and should discontinue usage immediately.

These Terms replace and supersede all prior or contemporaneous agreements, communications, or understandings between you and the Company, whether written or oral, relating to the access or use of the Platform or Services. Users are advised to review these Terms thoroughly before engaging with the Platform or availing any Services facilitated through it.

MyFNG reserves the right, at its sole discretion, to revise, update, or modify these Terms at any time in order to reflect changes in law, regulatory requirements, business practices, platform policies (including but not limited to Google Play Developer Program policies), or operational needs. Any such revisions shall be published on the Platform at www.myfng.in/terms-and-conditions and shall become effective upon publication.

You are responsible for periodically reviewing the Terms for updates. MyFNG is under no obligation to provide individual notifications of changes. Continued access to or use of the Platform or Services after the revised Terms are posted shall be deemed to constitute your acceptance of the updated Terms. References to "Terms" shall be understood to mean the most current version available on the Platform.

Information and content made available on the Platform are provided for general facilitation purposes only and should not be treated as a substitute for independent verification, inspection, or professional judgment by the User.

These Terms constitute an electronic contract under applicable Indian laws, including the Indian Contract Act, 1872 and the Information Technology Act, 2000, together with the rules and amendments made thereunder. This electronic record is generated by automated systems and does not require any physical, electronic, or digital signature to be valid and enforceable.

DEFINITIONS
Unless the context otherwise requires, the following capitalized terms, when used in these Terms and Conditions, shall have the meanings assigned to them below:
1. "Account" means the user account created by a User on the Platform for accessing and using the Services.
2. "Additional Services" means any services, repairs, replacements, or works requested by the User or identified during inspection that fall outside the scope of the selected Service Package.
3. "Affiliate" means any entity that directly or indirectly controls, is controlled by, or is under common control with MyFNG, where "control" shall mean ownership of more than fifty percent (50%) of the voting or equity interests of such entity.
4. "Applicable Law" means all statutes, enactments, acts of legislature, rules, regulations, notifications, guidelines, policies, directions, or orders having the force of law in India, as amended from time to time.
5. "Booking" means a service appointment requested by a User through the Platform and confirmed by MyFNG and/or a Partner Workshop for the provision of Services.
6. "Charges" means all amounts payable by the User in relation to the Services, including but not limited to service fees, labour charges, inspection fees, facilitation fees, cost of spare parts, taxes, levies, or any other applicable charges.
7. "Company" means MyFNG Autocare Private Limited (operating under the brand name "MyFNG"), and includes its successors and permitted assigns.
8. "Content" means all text, graphics, images, logos, software, audio, video, data, information, and other material made available on or through the Platform, whether owned by MyFNG or licensed from third parties.
9. "Partner Workshop" means an independent third-party automobile service provider, garage, or workshop empanelled with or accessible through the Platform for providing automotive services to Users.
10. "Platform" means, collectively, the MyFNG website located at www.myfng.in, the MyFNG mobile application, and all associated digital interfaces, features, tools, and systems operated by the Company.
11. "Privacy Policy" means the policy published by MyFNG describing the collection, use, storage, and protection of User Data, as updated from time to time.
12. "Service Package" means a predefined bundle of automotive services displayed on the Platform with a defined scope, inclusions, exclusions, and indicative pricing.
13. "Services" means the technology-enabled facilitation services offered by MyFNG through the Platform, including but not limited to appointment scheduling, service coordination, customer support, communication, and related features, and expressly excludes the physical performance of automotive repairs or maintenance unless otherwise stated.
14. "Terms" means these Terms and Conditions, including all schedules, policies, guidelines, and documents incorporated herein by reference, as amended from time to time.
15. "User", "you", or "your" means any individual or entity that accesses, browses, registers on, or uses the Platform or avails any Services through the Platform.
16. "User Data" means all information, details, data, documents, images, or content provided or generated by a User while accessing or using the Platform, including personal information, vehicle information, service history, and communication records.
17. "Vehicle" means any passenger car or automobile registered in India and owned, leased, or lawfully used by the User in respect of which Services are requested through the Platform.

SERVICES
1. Nature of Services
MyFNG provides a technology-enabled facilitation platform that enables Users to discover, request, schedule, and manage automotive maintenance, repair, inspection, and roadside support services offered by independent third-party service providers ("Partner Workshops" and "RSA Partners"). MyFNG's role is strictly limited to providing digital infrastructure, coordination tools, and customer support to enable such interactions.

2. No Direct Provision of Automotive or Roadside Services
MyFNG does not itself perform, operate, supervise, or control any physical automotive or roadside services, including but not limited to vehicle inspection, repair, replacement of parts, diagnostics, towing, jump-start assistance, or on-road support, unless expressly stated in writing. All such services are carried out solely by independent third-party service providers.

3. Service Facilitation Scope
The Services facilitated through the Platform may include, without limitation:
- Periodic and general car servicing
- Mechanical, electrical, and diagnostic assistance
- Car air-conditioning, battery, tyre, and wheel-related services
- Roadside Assistance (RSA), including towing, jump-start support, flat tyre assistance, emergency fuel delivery (where available), and minor on-road assistance
- Appointment scheduling and booking confirmations
- Service coordination and communication
- Sharing of estimates, updates, images, or service status (where available)
- Customer support and escalation assistance

Availability of specific Services may vary by location, time, vehicle type, and third-party service provider capacity.

4. Service Packages, RSA Requests, and Additional Services
Certain Services may be offered as predefined Service Packages with defined inclusions and exclusions. Roadside Assistance services are typically provided on a request or emergency basis and may be subject to distance limits, service caps, or separate Charges.
Any work or assistance beyond the stated scope of a Service Package or RSA request shall be treated as Additional Services and shall be performed only after obtaining the User's consent and approval of applicable Charges.

5. Indicative Information and Response Times
Any pricing, response times, distance coverage, or estimated arrival times displayed on the Platform for RSA or other Services are indicative only. Actual response times and costs may vary due to traffic conditions, location accessibility, weather, availability of service providers, vehicle condition, or other external factors beyond MyFNG's control.

6. Appointment-Based and On-Demand Services
- Regular car servicing and repair Services are provided on an appointment-only basis.
- RSA services may be provided on an on-demand or emergency basis, subject to availability and operational feasibility.
- MyFNG does not guarantee immediate assistance or minimum response times.

7. Right to Modify, Limit, or Discontinue Services
MyFNG reserves the right, at its sole discretion, to add, modify, restrict, suspend, or discontinue any Service, Service Package, RSA feature, coverage area, pricing structure, or Platform functionality at any time, whether temporarily or permanently, without prior notice.

8. No Warranty or Guarantee by MyFNG
MyFNG does not provide any warranty, assurance, or guarantee with respect to quality, outcomes, timeliness, or prevention of future breakdowns. Any warranty, if offered, is provided solely by the respective third-party service provider and subject to their terms.

9. No Agency or Employment Relationship
Nothing in these Terms shall be construed to create any partnership, agency, employment, franchise, or joint venture relationship between MyFNG and any Partner Workshop, RSA Partner, or User.

ELIGIBILITY
1. Age and Legal Capacity
Access to and use of the Platform and Services is available only to individuals who are at least eighteen (18) years of age and are legally competent to enter into a binding contract under Applicable Law.
2. Authority to Act
If you are using the Platform on behalf of any organization or legal entity, you represent and warrant that you have full authority to bind such entity to these Terms.
3. Vehicle Ownership or Lawful Use
You must be the lawful owner, authorized user, or duly permitted custodian of the Vehicle in respect of which Services are requested.
4. Accurate Information Requirement
You agree to provide true, accurate, current, and complete information.
5. Technical and Access Requirements
You must have a compatible device, active internet connectivity, and ability to receive calls/messages/notifications.
6. Compliance with Laws and Platform Policies
You agree to use the Platform and Services in compliance with all Applicable Laws and these Terms.
7. Right to Refuse or Restrict Access
MyFNG may refuse registration, restrict access, suspend, or terminate eligibility where criteria are not met or misuse is detected.

USE OF SERVICES
1. Permitted Use
Subject to these Terms, MyFNG grants a limited, personal, non-exclusive, non-transferable right to use the Platform.
2. Account Responsibility
You are solely responsible for credentials and all account activities.
3. Service Requests and Approvals
All service requests must be initiated through the Platform and Additional Services require your explicit approval.
4. Appointment-Based and On-Demand Services
Availability and timelines are not guaranteed.
5. Vehicle Handover and Inspection
Remove personal belongings before service and inspect vehicle on completion.
6. Fair and Responsible Use
No false/fraudulent requests, abuse, or harassment.
7. Communication and Consent
You consent to service-related communication via call/SMS/email/notifications.
8. Compliance with Instructions
You agree to follow reasonable safety and service instructions.
9. Suspension for Misuse
MyFNG may suspend access for breach, abuse, non-payment, or risk.
10. No Ownership or Rights
Use of Platform does not grant ownership rights.

SUPPORT
Email: info@myfng.in
Helpline: +91-9152307030
Support Hours: Monday to Sunday, 10:00 a.m. to 7:00 p.m. IST (excluding holidays / maintenance windows)

Support is facilitative in nature and does not replace obligations of third-party service providers. Response times vary.

PROHIBITED USAGE OF THE PLATFORM
Users shall not:
- Engage in unlawful/fraudulent use
- Misrepresent identity or service details
- Abuse RSA/non-emergency repeated calls
- Interfere with platform security/operations
- Reverse engineer or inject harmful code
- Infringe intellectual property rights
- Harass or abuse staff/service providers
- Bypass payment/workflow safeguards

MyFNG may preserve and disclose records as required by law and may suspend/terminate access immediately for violations.

USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS
User submissions are non-confidential unless agreed otherwise in writing. By submitting feedback/comments/content, you grant MyFNG a worldwide, perpetual, royalty-free, transferable, sublicensable license to use such submissions for service and business purposes, subject to law.

USER DATA
You must provide accurate data. MyFNG may collect/process/share data for booking, support, compliance, analytics, payment, fraud prevention, and service coordination in accordance with Applicable Law and the Privacy Policy.

INTELLECTUAL PROPERTY RIGHTS
All Platform IP belongs to MyFNG or its licensors. Users get only a limited revocable usage right and must not copy, distribute, reverse engineer, or commercially exploit Platform IP without written consent.

LICENSE
Subject to compliance with these Terms, MyFNG grants a limited, revocable, non-exclusive, non-transferable, non-sublicensable license for personal lawful use only.

LIMITATION OF LIABILITY
MyFNG is a facilitation platform and does not physically perform services. To the maximum extent permitted by law, MyFNG disclaims indirect/consequential damages and limits aggregate liability as permitted under law and service context.

EXEMPTIONS TO LIABILITY OF COMPANY
MyFNG is not liable for third-party acts/omissions, pre-existing vehicle issues, delays/unavailability in RSA, force majeure, user negligence, personal belongings left in vehicle, technical outages, and lawful compliance actions, subject to non-excludable statutory rights.

BILLING / CHARGES
Charges may include service fees, labour, parts, facilitation fees, taxes, towing/RSA charges, and other levies. Pricing shown may be indicative; final charges can vary based on inspection, additional work, location, and taxes. Additional Services require user approval.

CANCELLATION AND REFUND
Cancellation/refund eligibility depends on service stage, dispatch status, and incurred charges. Once service/dispatch starts, refunds may be restricted or unavailable as per these Terms and applicable law.

DISPUTE RESOLUTION
Parties should first attempt amicable resolution. Unresolved disputes are subject to arbitration under the Arbitration and Conciliation Act, 1996 (as amended), with seat/venue at Thane, Mumbai, Maharashtra, India, subject to applicable law.

GOVERNING LAW
These Terms are governed by laws of India. Subject to dispute resolution terms, courts at Thane, Maharashtra, India shall have jurisdiction, as permitted by law.

GENERAL PROVISIONS
Entire Agreement, Severability, No Waiver, Assignment, Force Majeure, Survival, Electronic Records, and Interpretation provisions apply.

TERMINATION
Users may stop using Platform anytime; MyFNG may suspend/terminate for breach, misuse, fraud, legal/security/operational risk, or legal requirements. Surviving clauses remain enforceable post-termination.

INDEMNIFICATION
User agrees to indemnify and hold harmless MyFNG and related parties from claims/losses arising out of breach, misuse, legal violations, false data, third-party disputes attributable to user conduct, and negligent/willful acts.

SUPPORT / CONTACTING YOU
Customer Support Helpline: +91-9152307030
Email: info@myfng.in
Grievance Officer:
- Name: Nitish Jha
- Mobile: +91-7977118621
- Email: info@myfng.in

By using the Platform and Services, you acknowledge and agree to these Terms and Conditions.
`;

export default function TermsAndConditionsPage() {
  return (
    <main className="bg-white">
      <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold text-gray-900">Terms and Conditions</h1>
        <p className="mt-2 text-sm text-gray-500">Last updated: February 27, 2026</p>
        <div className="mt-6 rounded-lg border border-gray-200 bg-gray-50 p-4 sm:p-6">
          <pre className="whitespace-pre-wrap font-sans text-sm leading-6 text-gray-800">
            {TERMS_CONTENT}
          </pre>
        </div>
      </div>
    </main>
  );
}
