export const metadata = {
  title: 'Terms and Conditions | MyFNG',
  description: 'MyFNG Terms and Conditions',
};

const TERMS_CONTENT = `Effective Date: March 2026

CONTRACTUAL RELATIONSHIP
My FNG Autocare Private Limited, a company duly incorporated under the Companies Act, 2013 and having its registered office at A/309, Centrum Business Square, Road No. 16, Wagle Industrial Estate, Thane (West), Thane - 400604, Maharashtra, India (“My FNG”, “Company”, “we”, “us”, or “our”), owns and operates a digital platform under the brand name My FNG. The Platform enables users to discover, schedule, and manage car maintenance, repair, inspection, and other related automotive services offered by independent third-party service providers (“Partner Workshops”).
These Terms & Conditions (“Terms”) govern your access to and use of the My FNG website available at www.myfng.in (“Website”) and the My FNG mobile application (“App”), including all associated features, content, functionalities, and services provided through them (collectively referred to as the “Services”). The Website and the App are together referred to as the “Platform.”
These Terms constitute a legally binding agreement between My FNG and any person who accesses or uses the Platform (“User”, “you”, or “your”). By accessing, visiting, registering on, downloading, or using the Platform, or by availing any Services through it, you acknowledge that you have read, understood, and agreed to be bound by these Terms, thereby establishing a contractual relationship between you and the Company.
If you do not agree with any part of these Terms, you must not access or use the Platform or Services and should discontinue usage immediately.
These Terms supersede and replace all prior or contemporaneous agreements, communications, or understandings between you and the Company, whether written or oral, relating to the access to or use of the Platform or Services. Users are advised to review these Terms carefully before using the Platform or availing any Services facilitated through it.
My FNG reserves the right, at its sole discretion, to modify, revise, or update these Terms at any time in order to reflect changes in applicable laws, regulatory requirements, business practices, operational needs, or platform policies (including but not limited to Google Play Developer Program policies). Any such updates shall be published on the Platform at https://myfng.in/terms-and-conditions and shall become effective immediately upon publication.
You are responsible for periodically reviewing these Terms for updates. My FNG shall not be obligated to provide individual notifications of such changes. Your continued access to or use of the Platform or Services after any revised Terms are posted shall constitute your acceptance of the updated Terms. References to “Terms” shall refer to the most current version available on the Platform.
Information, listings, and content made available on the Platform are provided for general facilitation purposes only and should not be considered a substitute for independent verification, inspection, or professional judgment by the User.
These Terms constitute an electronic contract under applicable Indian laws, including the Indian Contract Act, 1872 and the Information Technology Act, 2000, along with the rules and amendments made thereunder. This electronic record is generated by automated systems and does not require any physical, electronic, or digital signature to be valid and enforceable.


DEFINITIONS
Unless the context otherwise requires, the following capitalized terms used in these Terms & Conditions shall have the meanings assigned to them below. Words denoting the singular shall include the plural and vice versa, and words denoting any gender shall include all genders.
1.	“Account” means the registered user account created by a User on the Platform for the purpose of accessing and using the Services.
2.	“Additional Services” means any services, repairs, replacements, inspections, or other works requested by the User or identified during inspection that fall outside the scope of the selected Service Package.
3.	“Affiliate” means any entity that directly or indirectly controls, is controlled by, or is under common control with My FNG, where “control” means ownership of more than fifty percent (50%) of the voting rights or equity interests of such entity.
4.	“Applicable Law” means all statutes, enactments, acts of legislature, rules, regulations, notifications, circulars, guidelines, policies, directions, or orders having the force of law in India, as amended or re-enacted from time to time.
5.	“Booking” means a service request or appointment initiated by a User through the Platform and confirmed by My FNG and/or a Partner Workshop for the provision of automotive services.
6.	“Charges” means all amounts payable by the User in relation to the Services, including but not limited to service fees, labour charges, inspection fees, facilitation charges, cost of spare parts, applicable taxes, levies, and any other applicable charges.
7.	“Company” means My FNG Autocare Private Limited, operating under the brand name “My FNG”, and includes its affiliates, successors, and permitted assigns.
8.	“Content” means all text, graphics, images, logos, designs, software, audio, video, data, information, and other material made available on or through the Platform, whether owned by My FNG or licensed from third parties.
9.	“Partner Workshop” means an independent third-party automobile service provider, garage, or workshop that is listed, empanelled, or otherwise accessible through the Platform for providing automotive services to Users.
10.	“Platform” means collectively the My FNG website located at www.myfng.in, the My FNG mobile application, and all associated digital interfaces, features, tools, systems, and technologies operated by the Company.
11.	“Privacy Policy” means the policy published by My FNG describing the collection, use, storage, and protection of User Data, as updated or amended from time to time.
12.	“Service Package” means a predefined bundle of automotive services displayed on the Platform with a defined scope, inclusions, exclusions, and indicative pricing.
13.	“Services” means the technology-enabled facilitation services provided by My FNG through the Platform, including but not limited to appointment scheduling, service coordination, communication, customer support, and related features, and expressly excludes the physical performance of automotive repairs, maintenance, or inspection unless explicitly stated otherwise.
14.	“Terms” or “Terms & Conditions” means these Terms & Conditions, including all schedules, policies, guidelines, and documents incorporated herein by reference, as amended from time to time.
15.	“User”, “you”, or “your” means any individual, company, partnership, or legal entity that accesses, browses, registers on, or uses the Platform or avails any Services through the Platform.
16.	“User Data” means all information, details, data, documents, images, or content provided or generated by a User while accessing or using the Platform, including personal information, vehicle information, service history, and communication records.
17.	“Vehicle” means any passenger car or automobile registered in India and owned, leased, or lawfully used by the User in respect of which Services are requested through the Platform.

SERVICES
1. Nature of Services
My FNG provides a technology-enabled facilitation platform that enables Users to discover, request, schedule, and manage automotive maintenance, repair, inspection, and roadside support services offered by independent third-party service providers (“Partner Workshops” and “RSA Partners”).
My FNG’s role is strictly limited to providing digital infrastructure, coordination tools, and customer support to enable such interactions between Users and service providers.
2. No Direct Provision of Automotive or Roadside Services
My FNG does not itself perform, operate, supervise, or control any physical automotive or roadside services, including but not limited to vehicle inspection, repair, replacement of parts, diagnostics, towing, jump-start assistance, or on-road support, unless expressly stated in writing.
All such services are performed solely by independent third-party service providers.
3. Service Facilitation Scope
The Services facilitated through the Platform may include, without limitation:
•	Periodic and general car servicing
•	Mechanical, electrical, and diagnostic assistance
•	Car air-conditioning, battery, tyre, and wheel-related services
•	Roadside Assistance (RSA), including:
	Vehicle towing
	Battery jump-start support
	Flat tyre assistance
	Emergency fuel delivery (where available)
	Minor on-road mechanical or electrical assistance
•	Appointment scheduling and booking confirmations
•	Service coordination and communication between Users and service providers
•	Sharing of estimates, updates, images, or service status (where available)
•	Customer support and escalation assistance
Availability of specific Services may vary depending on location, time, vehicle type, operational limitations, and the availability of Partner Workshops or RSA Partners.
4. Service Packages, RSA Requests, and Additional Services
Certain Services may be offered as predefined Service Packages with defined inclusions and exclusions.
Roadside Assistance services are typically provided on a request or emergency basis and may be subject to distance limits, service caps, or separate Charges.
Any work, repair, or assistance beyond the stated scope of a Service Package or RSA request shall be treated as Additional Services and shall only be performed after obtaining the User’s consent and approval of the applicable Charges.
5. Indicative Information and Response Times
Any pricing, response times, distance coverage, or estimated arrival times displayed on the Platform for RSA or other Services are indicative only.
Actual response times and costs may vary due to factors including but not limited to:
•	Traffic conditions
•	Location accessibility
•	Weather conditions
•	Availability of service providers
•	Vehicle condition
•	Operational constraints
Such factors are beyond the control of My FNG.
6. Appointment-Based and On-Demand Services
•	Regular car servicing and repair Services are generally provided on an appointment-only basis.
•	Roadside Assistance (RSA) services may be provided on an on-demand or emergency basis, subject to availability and operational feasibility.
•	My FNG does not guarantee immediate assistance or minimum response times.
7. Right to Modify, Limit, or Discontinue Services
My FNG reserves the right, at its sole discretion, to add, modify, restrict, suspend, or discontinue any Service, Service Package, RSA feature, coverage area, pricing structure, or Platform functionality at any time, whether temporarily or permanently, without prior notice.
8. No Warranty or Guarantee by My FNG
My FNG does not provide any warranty, assurance, or guarantee with respect to:
•	The quality or outcome of services provided by Partner Workshops or RSA Partners
•	The timeliness of service delivery or response
•	The prevention of future breakdowns, failures, or emergencies
Any warranty or service assurance, if offered, is provided solely by the respective third-party service provider and shall be subject to their individual terms and conditions.
9. No Agency or Employment Relationship
Nothing in these Terms shall be construed to create any partnership, agency, employment, franchise, or joint venture relationship between My FNG and any Partner Workshop, RSA Partner, or User.
All third-party service providers operate independently and are solely responsible for the services they perform.

ELIGIBILITY
1. Age and Legal Capacity
Access to and use of the Platform and Services is available only to individuals who are at least eighteen (18) years of age and are legally competent to enter into a binding contract under Applicable Law.
By accessing or using the Platform, you represent and warrant that you meet these eligibility requirements.
2. Authority to Act
If you are accessing or using the Platform on behalf of any organization, company, partnership, or other legal entity, you represent and warrant that you have the full authority and legal capacity to bind such entity to these Terms.
In such cases, references to “User”, “you”, or “your” shall include the relevant entity.
3. Vehicle Ownership or Lawful Use
You must be the lawful owner, authorized user, or duly permitted custodian of the Vehicle in respect of which Services are requested through the Platform.
My FNG shall not be responsible for verifying the ownership, registration status, or usage rights of any Vehicle.
4. Accurate Information Requirement
You agree to provide true, accurate, current, and complete information while:
•	creating an Account
•	requesting Services
•	communicating through the Platform
This includes personal details, vehicle information, and location data where applicable.
My FNG reserves the right to suspend, restrict, or deny access if any information provided is found to be false, inaccurate, misleading, or incomplete.
5. Technical and Access Requirements
To access and use the Platform, you must have:
•	A compatible device and supported operating system
•	Active internet connectivity
•	The ability to receive calls, SMS messages, or platform notifications
My FNG does not guarantee uninterrupted, secure, or error-free access to the Platform and shall not be liable for access issues arising from technical limitations, connectivity failures, or third-party service disruptions beyond its control.
6. Compliance with Laws and Platform Policies
You agree to use the Platform and Services in compliance with:
•	all Applicable Laws
•	these Terms & Conditions
•	any guidelines, policies, or instructions communicated by My FNG from time to time.
Individuals who are legally restricted, disqualified, or prohibited by law or court order from entering into contractual relationships are not eligible to use the Platform.
7. Right to Refuse or Restrict Access
My FNG reserves the right, at its sole discretion, to refuse registration, restrict access, suspend, or terminate eligibility to use the Platform or Services, either temporarily or permanently, without prior notice, where:
•	Eligibility criteria are not met
•	False or misleading information is provided
•	Misuse, abuse, or fraudulent activity is detected
•	Continued access poses legal, operational, or security risks




USE OF SERVICES
1. Permitted Use
Subject to compliance with these Terms, My FNG grants the User a limited, personal, non-exclusive, non-transferable, and revocable right to access and use the Platform and Services solely for lawful purposes related to obtaining automotive maintenance, repair, inspection, or roadside assistance services for the User’s own Vehicle.
2. Account Responsibility
Where account creation is required, the User is solely responsible for:
•	Maintaining the confidentiality of account credentials
•	All activities carried out through the User’s Account
•	Promptly notifying My FNG of any unauthorized access, suspected misuse, or security breach
My FNG shall not be liable for any loss or damage arising from unauthorized use of the User’s Account.
3. Service Requests and Approvals
•	All service requests must be initiated through the Platform in the manner prescribed.
•	The User shall review service descriptions, scope, inclusions, exclusions, and applicable Charges before confirming a Booking.
•	Any Additional Services, including repairs, part replacements, or extended RSA support, shall be undertaken only after the User’s express approval.
4. Appointment-Based and On-Demand Services
•	Non-emergency automotive Services are provided strictly on an appointment basis.
•	Roadside Assistance (RSA) services may be offered on an on-demand or emergency basis, subject to availability.
•	The User acknowledges that service availability, response times, and completion timelines are not guaranteed and may vary due to external factors.
5. Vehicle Handover and Inspection
The User agrees to:
•	Hand over the Vehicle in a condition reasonably suitable for inspection or service
•	Remove personal belongings and valuables from the Vehicle prior to service
•	Inspect the Vehicle at the time of delivery or completion of service
My FNG shall not be responsible for any personal items or valuables left in the Vehicle.
6. Fair and Responsible Use
The User shall not:
•	Place false, duplicate, or fraudulent service requests
•	Misuse Roadside Assistance services for non-emergency purposes or repeated unjustified requests
•	Interfere with service providers, Platform operations, or customer support processes
•	Harass, abuse, threaten, or behave inappropriately towards Partner Workshops, RSA Partners, or My FNG personnel
7. Communication and Consent
By using the Services, the User consents to receive communications from My FNG and its service partners, including calls, SMS messages, emails, and app notifications, for purposes related to:
•	Service coordination
•	Booking confirmations
•	Service updates and alerts
•	Customer support and issue resolution
•	Transactional communication
8. Compliance with Instructions
The User agrees to comply with all reasonable instructions, safety guidelines, and service-related directions communicated by My FNG, Partner Workshops, or RSA Partners during the course of service facilitation.
9. Suspension for Misuse
My FNG reserves the right to suspend, restrict, or terminate a User’s access to the Platform or Services, with or without prior notice, in the event of:
•	Breach of these Terms
•	Misuse or abuse of Services, including RSA misuse
•	Non-payment of applicable Charges
•	Conduct that poses legal, operational, reputational, or safety risks
10. No Ownership or Rights in Services
Use of the Platform or Services does not grant the User any ownership rights, intellectual property rights, or proprietary interest in the Platform, Content, or underlying systems, except for the limited right to access and use the Services in accordance with these Terms.

SUPPORT
1. Scope of Support Services
My FNG provides customer support to assist Users with matters relating to access to the Platform, service bookings, coordination with Partner Workshops or RSA Partners, and general queries regarding the Services facilitated through the Platform.
Such support is provided strictly on a facilitative basis and does not constitute the provision, supervision, control, or guarantee of any automotive or roadside service.
2. Modes of Support
The Company offers email-based and phone-based support, along with an online knowledge repository of frequently asked questions (FAQs) available on the Platform.
Support may be accessed through the following channels:
•	Email: support@myfng.in
•	Helpline: +91-9152307030
•	FAQs / Knowledge Base: Available on the Platform
Support is generally available Monday to Sunday between 10:00 a.m. and 7:00 p.m. (IST), excluding public holidays, technical outages, or scheduled maintenance periods.
3. Response and Availability
While My FNG endeavors to respond to support requests in a timely manner, response times may vary depending on factors such as:
•	the nature and complexity of the request
•	service location
•	availability of Partner Workshops or RSA Partners
•	operational capacity and support workload
My FNG does not guarantee resolution within any specific timeframe.
4. Support Limitations
The User acknowledges and agrees that:
•	My FNG support does not replace or substitute the obligations of Partner Workshops or RSA Partners.
•	Mechanical issues, service quality concerns, and execution-related matters remain the responsibility of the relevant third-party service provider.
•	My FNG does not control the method, manner, or execution of services performed by third-party providers.
5. Escalation and Facilitation
Where appropriate, My FNG may facilitate communication or escalation of issues raised by the User with the relevant Partner Workshop or RSA Partner.
Such facilitation shall not be construed as an admission of liability, responsibility, or operational control by My FNG.
6. Accuracy of Information
Any information, guidance, or assistance provided by My FNG support personnel is offered on a best-effort and informational basis only, based on details available at the time.
Such information should not be considered technical, mechanical, or professional advice.
7. Emergency and Roadside Situations
My FNG support services are not emergency response services.
For Roadside Assistance requests, facilitation is subject to:
•	availability of service providers
•	location accessibility
•	operational feasibility
•	third-party response capability
My FNG does not guarantee immediate assistance or specific response times.
8. User Conduct and Right to Refuse Support
My FNG reserves the right to refuse, restrict, or discontinue support services where a User:
•	engages in abusive, threatening, or inappropriate conduct
•	submits false or misleading information
•	repeatedly raises unreasonable, fraudulent, or frivolous requests
•	misuses the Platform or support channels

PROHIBITED USAGE OF THE PLATFORM
1. Unlawful or Unauthorized Use
The User shall not access or use the Platform or Services for any purpose that is unlawful, fraudulent, deceptive, malicious, or otherwise prohibited under Applicable Law or these Terms.
Any use of the Platform in violation of statutory, regulatory, or contractual obligations is strictly prohibited.
2. Misrepresentation and Fraud
The User shall not:
•	Impersonate Any Person Or Entity
•	Misrepresent Identity, Vehicle Ownership, Service Requirements, Or Location
•	Submit False, Misleading, Or Fabricated Information
•	Initiate Fraudulent, Duplicate, Or Deceptive Service Requests
3. Abuse of Services and RSA Misuse
The User shall not:
•	Misuse Or Repeatedly Abuse Roadside Assistance Services For Non-Emergency Situations
•	Generate Service Requests Without Genuine Intent To Avail The Services
•	Engage In Repeated Cancellations Or No-Shows Without Valid Justification
•	Cause Unnecessary Dispatch Or Operational Disruption To Partner Workshops Or RSA Partners
4. Interference with Platform Operations
The User shall not:
•	Attempt To Gain Unauthorized Access To The Platform, Servers, Databases, Or Systems
•	Reverse Engineer, Decompile, Disassemble, Or Attempt To Derive Source Code
•	Introduce Viruses, Malware, Or Any Harmful Code
•	Disrupt, Interfere With, Or Compromise The Security, Integrity, Or Performance Of The Platform
5. Misuse of Content and Intellectual Property
The User shall not copy, reproduce, distribute, publish, modify, transmit, or commercially exploit any Content available on the Platform without the prior written consent of My FNG, except as expressly permitted under these Terms.
6. Harassment and Inappropriate Conduct
The User shall not engage in abusive, threatening, defamatory, obscene, discriminatory, or otherwise inappropriate conduct toward Partner Workshops, RSA Partners, My FNG employees, agents, support personnel, or other Users.
7. Commercial Exploitation and Circumvention
The User shall not:
•	Use The Platform Or Services For Commercial Resale, Redistribution, Or Solicitation
•	Harvest Or Extract Data, Contact Details, Or Pricing Information For Competitive Purposes
•	Circumvent Pricing, Payment Mechanisms, Service Workflows, Or Platform Safeguards
8. Preservation of Records and Lawful Disclosure
In the event of a suspected violation of Applicable Law, these Terms, or the Privacy Policy, My FNG shall be entitled to preserve User-generated information and associated records for a minimum period of ninety (90) days, or for such longer period as may be required by law, for the purpose of complying with legal obligations or producing such information before governmental or regulatory authorities for investigation or enforcement purposes.
9. Disclosure and Transfer of User Information
My FNG may disclose, share, or transfer User-generated information:
•	To Its Affiliates Or Service Partners Where Necessary For Service Facilitation
•	To Governmental, Regulatory, Or Law Enforcement Authorities Where Required Or Permitted By Applicable Law
The User expressly consents to such disclosure or transfer.
In accordance with Applicable Law, My FNG shall transfer sensitive personal data or information to another body corporate or person in India or any other country only where such entity ensures a level of data protection comparable to that adhered to by My FNG, and where such transfer is necessary for performance of a lawful contract or based on the User’s consent.
10. Immediate Termination for Non-Compliance
Without prejudice to any other rights or remedies available under law or these Terms, My FNG reserves the right to immediately suspend or terminate the User’s access to the Platform or Services and to remove or disable access to any non-compliant information or content in the event of:
•	Violation Of Applicable Law
•	Breach Of These Terms Or The Privacy Policy
•	Conduct Posing Legal, Security, Or Operational Risks
11. Consequences and Remedies
My FNG may, at its sole discretion:
•	Cancel Pending Or Future Bookings
•	Restrict Or Permanently Block Access To The Platform
•	Recover Losses Or Damages Caused By The Violation
•	Initiate Legal Proceedings Or Cooperate With Law Enforcement Authorities
12. No Waiver
Any failure or delay by My FNG in enforcing any provision of this section shall not be construed as a waiver of it’s right to enforce such provision at any subsequent time.

USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS
1. User Submissions
The Platform may permit Users to submit reviews, ratings, comments, suggestions, feedback, images, messages, or other content in connection with the Services (“User Submissions”).
By providing any User Submission, you represent and warrant that such content is accurate to the best of your knowledge and does not violate Applicable Law or the rights of any third party.
2. Non-Confidential Nature of Submissions
Unless expressly stated otherwise in writing, all User Submissions shall be deemed non-confidential and non-proprietary.
My FNG shall not be under any obligation to treat such submissions as confidential or to provide any compensation in respect thereof.
3. License Grant
By submitting User Submissions through the Platform, you grant My FNG a worldwide, irrevocable, perpetual, non-exclusive, royalty-free, transferable, and sublicensable license to:
•	Use
•	Host
•	Store
•	Reproduce
•	Modify
•	Adapt
•	Publish
•	Translate
•	Distribute
•	Publicly display
•	Otherwise exploit
such User Submissions, in whole or in part, in any media or format, for purposes including but not limited to:
•	Service improvement
•	Analytics
•	Customer communication
•	Marketing and promotional activities
4. Moral Rights Waiver
To the extent permitted under Applicable Law, you irrevocably waive any moral rights or similar rights in respect of your User Submissions and agree not to assert such rights against My FNG or its affiliates.
5. Content Standards
You agree that User Submissions shall not:
•	Be False, Misleading, Or Deceptive
•	Be Defamatory, Abusive, Obscene, Or Offensive
•	Infringe Intellectual Property, Privacy, Or Publicity Rights
•	Contain Malware, Spam, Or Unauthorized Advertising
•	Violate Applicable Law Or Platform Policies
6. Monitoring and Removal
My FNG reserves the right, but not the obligation, to review, monitor, edit, restrict, or remove any User Submissions at its sole discretion, without prior notice, where such content:
•	Violates These Terms Or Applicable Law
•	Is Misleading, Harmful, Or Inappropriate
•	Poses Legal, Reputational, Or Operational Risk
7. No Endorsement
User Submissions reflect the opinions of the individual Users and do not represent the views, endorsements, or guarantees of My FNG.
My FNG does not verify the accuracy or completeness of User Submissions.
8. Responsibility for Submissions
You remain solely responsible for all User Submissions you provide and for any consequences arising from them.
My FNG shall not be liable for any loss, damage, or claims arising out of User Submissions posted by Users or third parties.
9. Use in Legal or Regulatory Proceedings
My FNG may reserve and disclose User Submissions and associated records where required by:
•	Applicable Law
•	Legal process
•	Governmental or regulatory authorities
or where necessary to protect the rights, safety, or property of My FNG, its Users, or the public.

USER DATA
1. Accuracy and Responsibility for User Data
The User represents and warrants that all information, data, documents, and details provided in connection with access to or use of the Platform, including personal information, vehicle details, location data, and service-related information (“User Data”), are true, accurate, current, and complete.
The User undertakes to maintain and promptly update such information to ensure its continued accuracy.
The User acknowledges that My FNG relies on the accuracy of User Data for facilitating Services. In the event that any User Data is found to be false, misleading, outdated, or incomplete, My FNG reserves the right to suspend or terminate the User’s access to the Platform and Services, without prejudice to any other rights available under Applicable Law.
________________________________________
2. Collection and Processing of User Data
My FNG may collect, receive, store, and process User Data in accordance with Applicable Law and its Privacy Policy for lawful purposes, including but not limited to:
•	Facilitating Service Bookings And Roadside Assistance Requests
•	Verifying And Validating Documents Or Service-Related Information
•	Coordinating With Partner Workshops, RSA Partners, And Other Service Providers
•	Communicating Service Updates, Confirmations, And Support Information
•	Processing Payments, Refunds, And Transaction Records
•	Ensuring Platform Security, Fraud Prevention, And Legal Compliance
________________________________________
3. Analytics and Platform Improvement
My FNG may use information and data relating to the User’s access to and use of the Platform and Services for analytics, trend identification, statistical analysis, and operational insights, with the objective of improving the effectiveness, efficiency, functionality, and user experience of the Platform.
Such data may be processed internally or shared with My FNG’s affiliates, group companies, or authorized service providers strictly for these purposes.
________________________________________
4. User Consent
By accessing or using the Platform or Services, the User expressly consents to the collection, use, storage, processing, and sharing of User Data as described in these Terms and the Privacy Policy.
The User further acknowledges that certain Services may not be available if required User Data is not provided or if consent is withdrawn, subject to Applicable Law.
________________________________________
5. Sharing and Disclosure of User Data
My FNG may disclose or share User Data:
•	With Partner Workshops, RSA Partners, Payment Gateways, Logistics Partners, And Other Service Providers, on a need-to-know basis for service facilitation
•	With Affiliates Or Group Companies for operational, analytical, or compliance purposes
•	With Governmental Authorities, Regulatory Bodies, Or Law Enforcement Agencies, where required or permitted under Applicable Law, including in connection with investigations, legal proceedings, or compliance obligations
________________________________________
6. Cross-Border and Third-Party Transfers
Subject to Applicable Law, My FNG may transfer User Data, including sensitive personal data or information, to any body corporate or person located within India or in any other country, provided that such entity ensures a level of data protection comparable to that maintained by My FNG, and where such transfer is necessary for the performance of a lawful contract or based on the User’s consent.
________________________________________
7. Data Retention
User Data shall be retained only for such period as is reasonably necessary to:
•	Fulfill the purposes for which it was collected
•	Comply with legal or regulatory requirements
•	Resolve disputes
•	Enforce these Terms
•	Meet legitimate business needs
Certain records may be retained for longer periods where required by Applicable Law.
________________________________________
8. Data Security
My FNG implements reasonable technical and organizational security measures designed to protect User Data against unauthorized access, alteration, disclosure, or destruction.
However, the User acknowledges that no system can be completely secure, and My FNG does not guarantee absolute security of User Data.
________________________________________
9. User Rights
Subject to Applicable Law, the User may have the right to:
•	Access and review User Data
•	Correct inaccurate information
•	Request deletion of User Data
•	Withdraw consent for certain processing activities
Such requests shall be handled in accordance with the procedures set out in the Privacy Policy and applicable legal requirements.
________________________________________
10. Governing Policy
The collection, use, processing, storage, and protection of User Data are further governed by My FNG’s Privacy Policy, which forms an integral part of these Terms.
In the event of any inconsistency between these Terms and the Privacy Policy, the Privacy Policy shall prevail in matters relating to data protection and privacy.

INTELLECTUAL PROPERTY RIGHTS
1. Ownership of Intellectual Property
All intellectual property rights in and to the Platform, including but not limited to the Website, mobile application, software, source code, object code, user interfaces, workflows, designs, text, graphics, images, logos, icons, trademarks, service marks, trade names, audio, video, data compilations, and any other content or material made available on or through the Platform (“Platform IP”), are owned by or lawfully licensed to My FNG Autocare Private Limited, unless expressly stated otherwise.
________________________________________
2. Protection of Rights
The Platform IP is protected under applicable intellectual property laws, including copyright, trademark, and other proprietary rights under Indian law and international conventions.
No rights, title, or interest in the Platform IP are transferred to the User except as expressly provided under these Terms.
________________________________________
3. Limited Right of Use
Subject to compliance with these Terms, My FNG grants the User a limited, revocable, non-exclusive, non-transferable, and non-sublicensable right to access and use the Platform and Platform IP solely for personal and lawful use in connection with availing the Services.
Any use beyond this limited purpose is strictly prohibited.
________________________________________
4. Restrictions
The User shall not, directly or indirectly:
•	Copy, Reproduce, Modify, Adapt, Translate, Distribute, Publish, Transmit, Display, Perform, Or Create Derivative Works From Any Part Of The Platform Or Content
•	Reverse Engineer, Decompile, Disassemble, Or Attempt To Extract The Source Code Or Underlying Structure Of The Platform
•	Remove, Alter, Or Obscure Any Copyright, Trademark, Or Proprietary Notices
•	Use The Company’s Name, Trademarks, Logos, Or Branding For Any Commercial, Promotional, Or Misleading Purpose Without Prior Written Consent
•	Use The Platform Or Content For Any Commercial Purpose Unless Expressly Authorized
Any violation of these restrictions shall constitute a material breach of these Terms.
________________________________________
5. User Submissions and Feedback
Any feedback, suggestions, ideas, reviews, or other content submitted by the User to My FNG shall not confer any ownership rights on the User.
Such submissions shall be governed by the applicable clause relating to User Comments, Feedback and Other Submissions, and My FNG shall be entitled to use them in accordance with those Terms.
________________________________________
6. Third-Party Intellectual Property
Certain content or materials available on the Platform may belong to third parties, including Partner Workshops, service providers, or licensors.
The User acknowledges that all such third-party intellectual property remains the property of its respective owners and agrees not to infringe upon such rights.
________________________________________
7. Enforcement and Remedies
Any unauthorized use, infringement, or misuse of the Platform IP may result in immediate suspension or termination of access to the Platform and Services, in addition to any civil or criminal remedies available to My FNG under Applicable Law.
________________________________________
8. No Waiver
Failure by My FNG to enforce any intellectual property rights or provisions of these Terms shall not constitute a waiver of such rights or limit My FNG’s ability to enforce them at a later time.

USER CONTENT AND FEEDBACK
By submitting reviews, ratings, comments, images, feedback, or other content through the Platform (“User Content”), the User grants My FNG a worldwide, non-exclusive, royalty-free, transferable license to use, reproduce, modify, publish, display, and distribute such User Content for the purpose of operating, improving, and promoting the Platform and Services. The User represents that they own or have the necessary rights to submit such content and that such content does not violate any third-party rights or Applicable Law.

LICENSE
1. Grant of License
Subject to the User’s continued compliance with these Terms, My FNG grants the User a limited, non-exclusive, non-transferable, non-sublicensable, and revocable license to:
(a) access and use the My FNG mobile application on the User’s personal device solely for the purpose of availing the Services; and
(b) access and use any content, information, data, and related materials made available through the Platform strictly in connection with the User’s lawful use of the Services.
All rights not expressly granted under this License are reserved by My FNG and its licensors.
________________________________________
2. Scope and Purpose
The License granted under these Terms is provided solely for personal and non-commercial use.
The User acknowledges that the Platform is made available as a facilitative tool, and that use of the Platform does not confer any proprietary or ownership rights in the Platform or its Content.
________________________________________
3. Restrictions on Use
Except as expressly permitted under these Terms, the User shall not, directly or indirectly:
•	Use, Copy, Reproduce, Adapt, Modify, Translate, Or Create Derivative Works Based Upon The Platform Or Content
•	Distribute, License, Sell, Assign, Transfer, Lease, Rent, Or Otherwise Exploit The Platform Or Services
•	Publicly Display, Publicly Perform, Transmit, Stream, Broadcast, Or Make Available Any Part Of The Platform
•	Circumvent, Disable, Or Interfere With Security-Related Features Or Access Controls
•	Use The Platform Or Services For Any Unlawful, Commercial, Or Competitive Purpose
Any use beyond the scope of this License shall constitute a material breach of these Terms.
________________________________________
4. No Implied Rights
The User expressly acknowledges and agrees that no licenses or rights are granted by implication or otherwise under any intellectual property rights owned or controlled by My FNG or its licensors, except for the limited License expressly granted under these Terms.
________________________________________
5. Ownership
The Platform, Services, and all intellectual property rights vested therein are and shall remain the exclusive property of My FNG or its licensors.
Nothing contained in these Terms shall be construed as transferring any ownership or proprietary interest to the User.
________________________________________
6. Termination of License
This License shall automatically and immediately terminate upon:
•	Any Breach Of These Terms By The User
•	Suspension Or Termination Of The User’s Access To The Platform
•	Discontinuation Of The Platform Or Services, In Whole Or In Part
Upon termination, the User shall immediately cease all access to and use of the Platform and its Content.
________________________________________
7. Survival
The termination of this License shall not affect provisions that by their nature are intended to survive termination, including but not limited to:
•	Intellectual Property Rights
•	Limitation of Liability
•	Indemnification
•	Governing Law and Jurisdiction

THIRD-PARTY PLATFORM DISTRIBUTION
The Platform may be made available through third-party distribution platforms such as mobile application stores. The User acknowledges that such third-party platforms may have their own terms and conditions governing downloads and use of applications. My FNG is not responsible for the policies or practices of such third-party platforms.
LIMITATION OF LIABILITY
1. Platform-as-a-Facilitator Disclaimer
The User expressly acknowledges and agrees that My FNG operates solely as a technology-enabled facilitation platform and does not itself provide, perform, supervise, or control any automotive repair, maintenance, inspection, or roadside assistance services.
All such services are performed exclusively by independent Partner Workshops or RSA Partners.
Accordingly, My FNG shall not be liable for any acts, omissions, representations, warranties, or conduct of such third-party service providers.
________________________________________
2. No Warranties or Guarantees
To the maximum extent permitted under Applicable Law, the Platform, Services, and Content are provided on an “as is” and “as available” basis, without any warranties or guarantees of any kind, whether express or implied, including but not limited to:
•	Merchantability
•	Fitness for a particular purpose
•	Accuracy or reliability
•	Availability or timeliness
•	Uninterrupted or error-free operation
________________________________________
3. Exclusion of Certain Damages
To the fullest extent permitted under Applicable Law, My FNG, its directors, officers, employees, agents, affiliates, and licensors shall not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, including but not limited to:
•	Loss of profits
•	Loss of business
•	Loss of data
•	Loss of goodwill
•	Loss of use of the Vehicle
•	Service delays
•	Economic loss
whether arising in contract, tort (including negligence), strict liability, or otherwise, even if advised of the possibility of such damages.
________________________________________
4. Third-Party Service Risks
My FNG shall not be liable for:
•	Quality, Workmanship, Or Outcome Of Services Provided By Partner Workshops Or RSA Partners
•	Delays, Non-Performance, Or Cancellation Of Services
•	Damage Arising From Pre-Existing Conditions, Normal Wear And Tear, Misuse, Accidents, Or External Factors
•	Towing-Related Damages, Delays, Or Route Decisions Made By Third-Party Operators
•	Battery Jump-Start, Fuel Delivery, Or Roadside Assistance Outcomes
________________________________________
5. Platform and Technical Limitations
My FNG shall not be responsible for any loss or damage arising from:
•	Platform Downtime, Technical Failures, Or System Maintenance
•	Network, Internet, Device, Or Software Compatibility Issues
•	Unauthorized Access, Data Breaches, Or Cyber Incidents Beyond Reasonable Control
________________________________________
6. Aggregate Liability Cap
Notwithstanding anything to the contrary contained herein, and to the maximum extent permitted under Applicable Law, the total aggregate liability of My FNG for any claims arising out of or relating to the Platform or Services shall not exceed:
the facilitation fee (if any) actually paid by the User to My FNG for the specific Service giving rise to the claim, or INR 1,000, whichever is lower.
________________________________________
7. User Responsibility and Assumption of Risk
The User acknowledges that automotive and roadside services inherently involve risks.
The User voluntarily assumes all risks associated with the use of the Services and agrees that My FNG shall not be liable for outcomes resulting from such inherent risks.
________________________________________
8. Mandatory Legal Rights
Nothing in these Terms shall exclude or limit any liability that cannot be excluded or limited under Applicable Law, including liability for fraud or willful misconduct where such exclusion is prohibited by law.

EXEMPTIONS TO LIABILITY OF THE COMPANY
Without prejudice to and in addition to the limitations set out under the Limitation of Liability clause, My FNG shall not be liable for any loss, damage, claim, cost, or expense arising out of or in connection with the following circumstances:
________________________________________
1. Acts or Omissions of Third-Party Service Providers
My FNG shall not be liable for any act, omission, negligence, misconduct, delay, or failure on the part of any Partner Workshop, RSA Partner, towing operator, technician, or any other third-party service provider, including but not limited to matters relating to workmanship quality, service outcomes, spare parts used, or service timelines.
________________________________________
2. Vehicle Condition and Pre-Existing Issues
My FNG shall not be responsible for:
•	Pre-existing Mechanical, Electrical, Structural, Or Cosmetic Issues
•	Normal Wear And Tear, Aging Components, Or Manufacturer Defects
•	Damage Arising From Prior Repairs, Modifications, Or Improper Maintenance
•	Issues Discovered During Or After Service That Were Not Reasonably Detectable Beforehand
________________________________________
3. Roadside Assistance and Emergency Services
My FNG shall not be liable for:
•	Delays In Arrival Or Non-Availability Of Roadside Assistance Services
•	Route Selection, Towing Method, Or Handling Decisions Taken By Towing Operators
•	Damage Occurring During Towing, Jump-Start, Fuel Delivery, Or On-Road Assistance
•	Consequential Losses Arising From Roadside Breakdowns Or Emergencies
________________________________________
4. Force Majeure Events
My FNG shall not be liable for any failure or delay in performance resulting from events beyond its reasonable control, including but not limited to:
•	Natural disasters
•	Floods or fires
•	Strikes or lockouts
•	Riots or civil disturbances
•	Pandemics
•	Government actions or restrictions
•	Power failures
•	Network outages
•	Acts of God
________________________________________
5. User Actions or Negligence
My FNG shall not be liable for losses arising from:
•	Incorrect, Incomplete, Or Misleading Information Provided By The User
•	Failure By The User To Follow Service Recommendations Or Safety Instructions
•	Unauthorized Third-Party Intervention Or Repairs
•	Improper Use, Handling, Or Storage Of The Vehicle After Service
________________________________________
6. Personal Belongings and Valuables
My FNG shall not be responsible for any loss, theft, or damage to personal belongings, valuables, documents, or accessories left inside the Vehicle before, during, or after service, including during towing or roadside assistance.
________________________________________
7. Pricing Variations and Additional Repairs
My FNG shall not be liable for:
•	Changes In Service Costs Due To Additional Repairs Identified After Inspection
•	Fluctuations In Spare Part Prices Or Tax Rates
•	Costs Arising From User-Approved Additional Services
________________________________________
8. Platform and Technical Issues
My FNG shall not be liable for:
•	Temporary Unavailability Of The Platform
•	Technical Malfunctions, Software Bugs, Or System Maintenance
•	Internet Connectivity Issues Or Device Incompatibility
•	Data Loss Or Unauthorized Access Beyond Reasonable Security Controls
________________________________________
9. No Guarantee of Outcomes
My FNG shall not be liable for:
•	Failure Of A Service To Achieve Expected Performance Improvements
•	Recurrence Of Mechanical Issues After Service
•	Any Indirect, Incidental, Or Consequential Damages Arising From Service Outcomes
________________________________________
10. Lawful Acts and Compliance Obligations
My FNG shall not be liable for actions taken in good faith to comply with:
•	Applicable Law
•	Court orders
•	Regulatory requirements
•	Lawful requests from governmental or law enforcement authorities
________________________________________
11. Statutory Rights
Nothing in this clause shall exclude or limit liability to the extent that such exclusion or limitation is not permitted under Applicable Law.

BILLING / CHARGES
1. Service Charges and Pricing Structure
Charges for Services facilitated through the Platform may include, without limitation, service fees, labour charges, inspection or diagnostic charges, facilitation fees, cost of spare parts, towing or Roadside Assistance charges, taxes, and any other applicable levies (“Charges”).
All Charges displayed or communicated on the Platform are provided on a best-effort and indicative basis, unless expressly stated as fixed.
________________________________________
2. Indicative Pricing and Estimates
Prices, estimates, or quotations shown on the Platform are indicative only and based on information available at the time of booking.
Final Charges may vary depending on factors including:
• Vehicle Condition And Inspection Findings
• Additional Repairs Or Replacements Identified During Service
• Availability And Cost Of Spare Parts
• Location, Distance, Or Response Time For Roadside Assistance Or Towing
• Applicable Taxes Or Statutory Levies
Any material change in Charges shall be communicated to the User, and Additional Services shall be undertaken only upon the User’s approval.
________________________________________
3. Service Packages
Certain Services may be offered as predefined Service Packages with specified inclusions and exclusions.
Any work or service falling outside the scope of the selected Service Package shall be treated as Additional Services and billed separately.
________________________________________
4. Roadside Assistance and Towing Charges
Roadside Assistance services such as towing, battery jump-start, fuel delivery, or on-road support may be charged based on factors including:
•	Distance
•	Time
•	Location
•	Vehicle type
•	Service complexity
Response times, coverage limits, and Charges for such services are not guaranteed and may vary depending on operational feasibility and third-party service provider availability.
________________________________________
5. Taxes and Statutory Levies
All Charges are exclusive of applicable taxes unless expressly stated otherwise.
Taxes such as GST or other statutory levies shall be charged as applicable under law and reflected in the final invoice.
________________________________________
6. Payment Methods
Payments may be made through payment methods made available on the Platform, including:
•	Digital payment gateways
•	UPI
•	Credit or debit cards
•	Net banking
•	Other permitted payment methods from time to time
Use of third-party payment services may be subject to their respective terms and conditions, for which My FNG shall not be responsible.
________________________________________
7. Payment Authorization
By confirming a Booking or approving Additional Services, the User authorizes My FNG and/or the relevant service provider to charge the applicable amount through the selected payment method.
The User agrees to ensure sufficient funds or credit availability to complete the transaction.
________________________________________
8. Non-Payment or Payment Failure
My FNG reserves the right to:
•	Suspend Or Cancel A Booking In Case Of Non-Payment Or Payment Failure
•	Withhold Service Delivery Until Payment Obligations Are Fulfilled
•	Recover Outstanding Amounts Through Lawful Means
________________________________________
9. Invoices and Billing Records
Invoices or billing summaries may be generated electronically and shared with the User through the Platform, email, or other communication channels.
The User is responsible for reviewing billing details and promptly raising any discrepancies.
________________________________________
10. Price Revisions
My FNG reserves the right to revise pricing, service fees, or Charges at any time for future Bookings.
Any such changes shall not affect Charges already confirmed and approved by the User for an existing Booking.
________________________________________
11. No Hidden Charges
My FNG endeavors to maintain transparency in pricing.
No Charges shall be levied without disclosure or User approval, except where required by law or due to circumstances beyond reasonable control, such as statutory tax changes.

CANCELLATION AND REFUND
1. Cancellation by User
The User may request cancellation of a Booking through the Platform or by contacting customer support, subject to the terms set out herein.
Cancellation requests shall be effective only upon confirmation by My FNG.
________________________________________
2. Cancellation Before Service Commencement
Where a cancellation request is made prior to the commencement of service or dispatch of a service provider, the User may be eligible for a refund of amounts paid, subject to deduction of any applicable administrative, inspection, or convenience charges, as communicated at the time of booking.
________________________________________
3. Cancellation After Service Commencement
No refunds shall be payable where:
•	Service Has Commenced, including inspection, diagnostics, towing dispatch, or on-road assistance
•	A Service Provider Has Been Assigned And Has Arrived At The Location
•	Parts Have Been Procured Or Services Have Been Partially Or Fully Rendered
In such cases, the User shall remain liable to pay all applicable Charges incurred up to the point of cancellation.
________________________________________
4. Roadside Assistance and Emergency Services
Cancellation of Roadside Assistance services, including towing, battery jump-start, fuel delivery, or emergency on-road support, may not be eligible for refunds once the service provider has been dispatched or has commenced travel toward the User’s location, irrespective of whether the service is ultimately availed.
________________________________________
5. Cancellation by My FNG
My FNG reserves the right to cancel a Booking in circumstances including, but not limited to:
•	Unavailability Of Partner Workshops Or RSA Partners
•	Inaccurate Or Incomplete Information Provided By The User
•	Safety, Legal, Or Operational Concerns
•	Non-Payment Or Payment Failure
In such cases, My FNG may, at its discretion, issue a refund for amounts paid for services not rendered.
________________________________________
6. Refund Eligibility and Mode
Refunds, where applicable and approved, shall be processed through the original mode of payment used by the User, unless otherwise required under Applicable Law or mutually agreed.
My FNG does not offer cash refunds.
________________________________________
7. Refund Timelines
Approved refunds shall be processed within a reasonable period, which may vary depending on the payment method, banking processes, or third-party payment gateway timelines.
My FNG shall not be responsible for delays caused by banks or payment service providers.
________________________________________
8. Non-Refundable Amounts
The following amounts shall generally be non-refundable:
•	Inspection, Diagnostic, Or Visit Charges
•	Towing Or RSA Dispatch Charges
•	Charges For Additional Services Approved By The User
•	Charges Incurred Due To User’s Absence, Non-Availability, Or Incorrect Information
________________________________________
9. Disputes and Clarifications
Any dispute regarding cancellation or refund must be raised within a reasonable time from the date of service or cancellation request.
My FNG shall review such disputes on a best-effort basis and communicate its decision to the User.
________________________________________
10. No Guarantee of Refund
The User acknowledges that refunds are not guaranteed and are subject to service status, involvement of third-party service providers, and compliance with this clause.
My FNG’s decision regarding refunds shall be final, subject to Applicable Law.
________________________________________
11. Statutory Rights
Nothing in this clause shall affect any statutory rights or remedies available to the User under Applicable Law that cannot be lawfully excluded.

CANCELLATION AND REFUND
1. Cancellation by User
The User may request cancellation of a Booking through the Platform or by contacting customer support, subject to the terms set out herein.
Cancellation requests shall be effective only upon confirmation by My FNG.
________________________________________
2. Cancellation Before Service Commencement
Where a cancellation request is made prior to the commencement of service or dispatch of a service provider, the User may be eligible for a refund of amounts paid, subject to deduction of any applicable administrative, inspection, or convenience charges, as communicated at the time of booking.
________________________________________
3. Cancellation After Service Commencement
No refunds shall be payable where:
•	Service Has Commenced, including inspection, diagnostics, towing dispatch, or on-road assistance
•	A Service Provider Has Been Assigned And Has Arrived At The Location
•	Parts Have Been Procured Or Services Have Been Partially Or Fully Rendered
In such cases, the User shall remain liable to pay all applicable Charges incurred up to the point of cancellation.
________________________________________
4. Roadside Assistance and Emergency Services
Cancellation of Roadside Assistance services, including towing, battery jump-start, fuel delivery, or emergency on-road support, may not be eligible for refunds once the service provider has been dispatched or has commenced travel toward the User’s location, irrespective of whether the service is ultimately availed.
________________________________________
5. Cancellation by My FNG
My FNG reserves the right to cancel a Booking in circumstances including, but not limited to:
•	Unavailability Of Partner Workshops Or RSA Partners
•	Inaccurate Or Incomplete Information Provided By The User
•	Safety, Legal, Or Operational Concerns
•	Non-Payment Or Payment Failure
In such cases, My FNG may, at its discretion, issue a refund for amounts paid for services not rendered.
________________________________________
6. Refund Eligibility and Mode
Refunds, where applicable and approved, shall be processed through the original mode of payment used by the User, unless otherwise required under Applicable Law or mutually agreed.
My FNG does not offer cash refunds.
________________________________________
7. Refund Timelines
Approved refunds shall be processed within a reasonable period, which may vary depending on the payment method, banking processes, or third-party payment gateway timelines.
My FNG shall not be responsible for delays caused by banks or payment service providers.
________________________________________
8. Non-Refundable Amounts
The following amounts shall generally be non-refundable:
•	Inspection, Diagnostic, Or Visit Charges
•	Towing Or RSA Dispatch Charges
•	Charges For Additional Services Approved By The User
•	Charges Incurred Due To User’s Absence, Non-Availability, Or Incorrect Information
________________________________________
9. Disputes and Clarifications
Any dispute regarding cancellation or refund must be raised within a reasonable time from the date of service or cancellation request.
My FNG shall review such disputes on a best-effort basis and communicate its decision to the User.
________________________________________
10. No Guarantee of Refund
The User acknowledges that refunds are not guaranteed and are subject to service status, involvement of third-party service providers, and compliance with this clause.
My FNG’s decision regarding refunds shall be final, subject to Applicable Law.
________________________________________
11. Statutory Rights
Nothing in this clause shall affect any statutory rights or remedies available to the User under Applicable Law that cannot be lawfully excluded.

DISPUTE RESOLUTION
1. Good Faith Resolution
In the event of any dispute, controversy, or claim arising out of or in connection with these Terms, the Platform, or the Services (“Dispute”), the User and My FNG shall first attempt to resolve the Dispute amicably and in good faith through mutual discussions.
The User may initiate such discussions by contacting My FNG through the support channels provided on the Platform.
________________________________________
2. Escalation and Internal Review
If the Dispute is not resolved through initial discussions within a reasonable period, My FNG may internally review the matter and facilitate further communication, including coordination with relevant Partner Workshops or service providers, where applicable.
Such facilitation shall not be construed as an admission of liability by My FNG.
________________________________________
3. Arbitration
Subject to Applicable Law, any Dispute that is not resolved amicably shall be referred to arbitration in accordance with the Arbitration and Conciliation Act, 1996, as amended from time to time.
•	The arbitration shall be conducted by a sole arbitrator appointed by My FNG.
•	The seat and venue of arbitration shall be Thane, Maharashtra, India, unless otherwise required by Applicable Law.
•	The arbitration proceedings shall be conducted in the English language.
The arbitral award shall be final and binding on the parties, subject to rights available under Applicable Law.
________________________________________
4. Jurisdiction for Non-Arbitrable Matters
Notwithstanding the foregoing, Disputes that are not capable of being resolved through arbitration under Applicable Law, or where arbitration is prohibited by law, shall be subject to the exclusive jurisdiction of the competent courts in Thane, Maharashtra, India.
________________________________________
5. Interim and Injunctive Relief
Nothing in this clause shall prevent My FNG from seeking interim, injunctive, or equitable relief from a court of competent jurisdiction to protect its:
•	Intellectual property rights
•	Confidential information
•	Platform integrity and security
________________________________________
6. Continued Use of Services
During the pendency of any Dispute, the User agrees to continue complying with these Terms and fulfilling all payment obligations, unless otherwise directed by My FNG or required under Applicable Law.
________________________________________
7. Costs
Each party shall bear its own costs and expenses incurred in relation to the dispute resolution process, unless otherwise determined by the arbitrator or required under Applicable Law.
________________________________________
8. Statutory Rights
Nothing in this clause shall restrict or exclude any statutory rights or remedies available to the User under Applicable Law that cannot be lawfully waived.

GOVERNING LAW
These Terms & Conditions, the Platform, and the Services shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles.
Subject to the Dispute Resolution clause, the competent courts located in Thane, Maharashtra, India, shall have exclusive jurisdiction over all matters arising out of or relating to these Terms, the Platform, or the Services, to the extent permitted under Applicable Law.
Nothing in this clause shall limit or restrict any statutory rights or remedies available to the User under Applicable Law that cannot be lawfully excluded or waived.

MODIFICATION OF TERMS
My FNG reserves the right to modify, amend, or update these Terms at any time to reflect changes in the Platform, Services, legal requirements, or business practices.
Any updated version of these Terms shall be published on the Platform with the revised “Effective Date.”
The User’s continued access to or use of the Platform after such updates constitutes acceptance of the revised Terms.
If the User does not agree with the updated Terms, the User must discontinue use of the Platform and Services.

GENERAL PROVISIONS
1. Entire Agreement
These Terms, together with the Privacy Policy and any other policies or guidelines referenced herein, constitute the entire agreement between the User and My FNG with respect to access to and use of the Platform and Services, and supersede all prior or contemporaneous agreements, communications, or understandings, whether written or oral.
________________________________________
2. Severability
If any provision of these Terms is held to be invalid, illegal, or unenforceable under Applicable Law, such provision shall be severed, and the remaining provisions shall remain in full force and effect to the maximum extent permitted by law.
________________________________________
3. No Waiver
Any failure or delay by My FNG in exercising or enforcing any right, power, or remedy under these Terms shall not constitute a waiver of such right, power, or remedy.
Any waiver shall be effective only if made in writing and signed by an authorized representative of My FNG.
________________________________________
4. Assignment
The User shall not assign, transfer, or delegate any rights or obligations under these Terms without the prior written consent of My FNG.
My FNG may freely assign or transfer these Terms, in whole or in part, including to an affiliate, successor entity, or in connection with a merger, acquisition, restructuring, or sale of assets.
________________________________________
5. Relationship of Parties
Nothing in these Terms shall be construed as creating any partnership, joint venture, agency, employment, or fiduciary relationship between the User and My FNG.
The User acknowledges that My FNG acts solely as an independent platform facilitator.
________________________________________
6. Force Majeure
My FNG shall not be liable for any failure or delay in performance of its obligations under these Terms where such failure or delay results from events beyond its reasonable control, including but not limited to:
• Acts of God
• Natural disasters
• Pandemics
• Strikes or labor disputes
• Government actions
• Network failures
• Power outages
• Technical breakdowns
________________________________________
7. Survival
Provisions which by their nature are intended to survive termination or expiration of these Terms shall remain in effect, including but not limited to:
• Intellectual Property Rights
• License Restrictions
• Limitation of Liability
• Exemptions to Liability
• Indemnification
• Dispute Resolution
• Governing Law
________________________________________
8. Headings
Headings used in these Terms are for convenience only and shall not affect the interpretation or construction of any provision.
________________________________________
9. Electronic Records and Communication
These Terms constitute an electronic record under the Information Technology Act, 2000 and applicable rules thereunder.
The User consents to receiving communications, notices, and records electronically through the Platform, email, or other digital means, and agrees that such communications shall have the same legal effect as written communications.
________________________________________
10. Interpretation
In these Terms, unless the context otherwise requires:
• Words in the singular include the plural, and vice versa
• References to “including” shall mean “including without limitation”
• References to any statute include amendments, modifications, or replacements thereof

TERMINATION
1. Termination by User
The User may discontinue use of the Platform at any time. Where the User has an active Booking or pending payment obligations, such obligations shall survive termination and must be settled in accordance with these Terms.
________________________________________
2. Termination or Suspension by My FNG
My FNG reserves the right, at its sole discretion, to suspend or terminate the User’s access to the Platform and Services, in whole or in part, with or without prior notice, in the event that:
•	The User breaches or violates these Terms or any applicable policies
•	The User provides false, misleading, or incomplete information
•	The User engages in fraudulent, abusive, or unlawful conduct
•	Continued access poses legal, security, or operational risks
•	Required by Applicable Indian Law, court order, or governmental authority
________________________________________
3. Immediate Termination
My FNG may immediately terminate access without prior notice where the User’s conduct:
•	Causes or is likely to cause harm to the Platform, other Users, service providers, or My FNG
•	Involves misuse of Roadside Assistance or repeated service abuse
•	Involves infringement of intellectual property rights
________________________________________
4. Effect of Termination
Upon termination:
•	The User’s right to access and use the Platform and Services shall immediately cease
•	Any pending or future Bookings may be cancelled
•	Outstanding Charges shall become immediately payable
•	The License granted under these Terms shall automatically terminate
________________________________________
5. No Liability for Termination
To the maximum extent permitted under Applicable Law, My FNG shall not be liable to the User or any third party for any loss or damage arising from suspension or termination of access in accordance with these Terms.
________________________________________
6. Survival of Rights and Obligations
Termination shall not affect provisions which by their nature are intended to survive termination, including but not limited to:
•	Intellectual Property Rights
•	License Restrictions
•	Limitation of Liability
•	Exemptions to Liability
•	Indemnification
•	Dispute Resolution
•	Governing Law
________________________________________
7. Re-Registration
Termination or suspension of access shall not create any obligation on My FNG to permit re-registration or future access to the Platform, unless expressly agreed in writing.

INDEMNIFICATION
The User agrees to indemnify, defend, and hold harmless My FNG, its directors, officers, employees, affiliates, licensors, and service providers from and against any and all claims, demands, actions, proceedings, losses, damages, liabilities, costs, and expenses (including reasonable legal fees) arising out of or in connection with:
________________________________________
1. Breach of Terms
Any breach or alleged breach of these Terms, the Privacy Policy, or any other policies applicable to the User’s access to or use of the Platform or Services.
________________________________________
2. Violation of Law
Any violation of Applicable Law, regulations, court orders, or governmental directions by the User in connection with the use of the Platform or Services.
________________________________________
3. Misuse of the Platform or Services
Any misuse, abuse, fraudulent activity, or unauthorized use of the Platform or Services, including misuse of Roadside Assistance, towing, or emergency services.
________________________________________
4. User Data and Submissions
Any claim arising from:
•	Inaccurate, misleading, or incomplete information provided by the User
•	User comments, feedback, reviews, images, or other submissions
•	Infringement of intellectual property rights, privacy rights, publicity rights, or other rights of any third party resulting from User submissions or conduct
________________________________________
5. Third-Party Interactions
Any dispute, claim, or liability arising directly or indirectly from the User’s interaction with Partner Workshops, RSA Partners, towing operators, or other third-party service providers, except to the extent caused solely by the willful misconduct of My FNG.
________________________________________
6. Negligence or Misconduct
Any negligent act, omission, or willful misconduct by the User in connection with the Platform, Services, or the Vehicle.
________________________________________
7. Defense and Cooperation
My FNG reserves the right to assume the exclusive defense and control of any matter subject to indemnification, and the User agrees to cooperate fully with My FNG in asserting any available defenses.
________________________________________
8. Survival
This Indemnification clause shall survive termination or expiration of these Terms.

SUPPORT / CONTACTING US
1. Scope of Support Services
My FNG provides customer support to assist Users with matters relating to access to the Platform, service bookings, coordination with Partner Workshops or RSA Partners, and general queries regarding the Services facilitated through the Platform.
Such support is provided strictly on a facilitative basis and does not constitute the provision, supervision, or guarantee of any automotive or roadside service.
________________________________________
2. Modes of Support
The Company offers an email-based and phone call–based support system, along with an online knowledge repository of frequently asked questions (FAQs) available on the Platform.
Users may contact My FNG support through the following channels:
• Customer Support Helpline: +91-9152307030
• Email: support@myfng.in
• FAQs / Knowledge Base: Available on the Platform
Support is available Monday to Saturday, between 10:00 a.m. and 7:00 p.m. (IST), excluding public holidays or scheduled maintenance periods.
________________________________________
3. Response and Availability
While My FNG endeavors to respond to support requests in a timely manner, response times may vary depending on:
• Nature of the request
• Service location
• Availability of third-party providers
• Operational capacity
My FNG does not guarantee resolution within any specific timeframe.
________________________________________
4. Support Limitations
The User acknowledges that:
• My FNG support does not substitute the obligations of Partner Workshops or RSA Partners
• Mechanical, service-quality, or execution-related issues remain the responsibility of the relevant third-party service provider
• My FNG does not control the manner or method in which third-party services are performed
________________________________________
5. Escalation and Facilitation
Where appropriate, My FNG may facilitate communication or escalation of issues raised by the User with the relevant Partner Workshop or RSA Partner.
Such facilitation shall not be construed as an admission of liability or responsibility by My FNG.
________________________________________
6. Grievance Redressal Officer
In accordance with Applicable Law, Users may escalate unresolved grievances to the Company’s designated Grievance Officer:
• Name: Nitish Jha
• Mobile: +91-7977118621
• Email: cs-reply@myfng.in
The Grievance Officer shall acknowledge and address grievances within a reasonable timeframe, in accordance with Applicable Law.
________________________________________
7. Accuracy of Information
Any information, guidance, or assistance provided by My FNG support personnel is offered on a best-effort and informational basis only, based on information available at the time, and should not be treated as technical, mechanical, or professional advice.
________________________________________
8. Emergency and Roadside Situations
My FNG support services are not emergency response services.
Roadside Assistance facilitation is subject to availability, location constraints, and third-party response capability.
My FNG does not guarantee immediate assistance or response times.
________________________________________
9. User Conduct and Right to Refuse Support
My FNG reserves the right to refuse, restrict, or discontinue support where a User:
• Engages in abusive, threatening, or inappropriate conduct
• Submits false or misleading information
• Repeatedly raises unreasonable or frivolous requests

By using the Platform and Services, you acknowledge and agree to these Terms and Conditions.
`;

export default function TermsAndConditionsPage() {
  return (
    <main className="bg-white">
      <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold text-gray-900">Terms and Conditions</h1>
        <p className="mt-2 text-sm text-gray-500">Last updated: February 27, 2026</p>
        <div className="mt-6 rounded-lg border border-gray-200 bg-gray-50 p-4 sm:p-6">
          <pre className="whitespace-pre-wrap font-sans text-sm leading-6 text-gray-800">
            {TERMS_CONTENT}
          </pre>
        </div>
      </div>
    </main>
  );
}
