import React from 'react';
import { Text } from 'react-native';

// Simple emoji-based icon component to replace MaterialCommunityIcons
export function Icon({ name, size = 24, color = '#000', style }: any) {
  const iconMap: Record<string, string> = {
    // Common icons
    'phone': '📞',
    'phone-off': '📵',
    'phone-forward': '📱',
    'whatsapp': '💬',
    'email': '📧',
    'account': '👤',
    'account-circle': '👤',
    'car': '🚗',
    'wrench': '🔧',
    'calendar': '📅',
    'calendar-clock': '⏰',
    'calendar-check': '✅',
    'map-marker': '📍',
    'magnify': '🔍',
    'plus': '➕',
    'pencil': '✏️',
    'eye': '👁️',
    'check': '✓',
    'check-circle': '✅',
    'close': '✕',
    'close-circle': '❌',
    'alert-circle': '⚠️',
    'information': 'ℹ️',
    'text': '📝',
    'content-copy': '📋',
    'script-text-outline': '📄',
    'chevron-up': '▲',
    'chevron-down': '▼',
    'chevron-left': '◀',
    'chevron-right': '▶',
    'home': '🏠',
    'cog': '⚙️',
    'logout': '🚪',
    'menu': '☰',
    'dots-vertical': '⋮',
    'priority-high': '🔴',
    'history': '🕐',
    'chart-line': '📊',
    'cash': '💰',
    'trophy': '🏆',
    'star': '⭐',
    'bell': '🔔',
    'bookmark': '🔖',
    'filter': '🔽',
    'sort': '↕️',
    'download': '⬇️',
    'upload': '⬆️',
    'refresh': '🔄',
    'share': '↗️',
    'delete': '🗑️',
    'link': '🔗',
    'attachment': '📎',
    'image': '🖼️',
    'camera': '📷',
    'video': '🎥',
    'file': '📁',
    'folder': '📂',
    'document': '📄',
    'clipboard': '📋',
    'lock': '🔒',
    'unlock': '🔓',
    'key': '🔑',
    'shield': '🛡️',
    'warning': '⚠️',
    'error': '❗',
    'success': '✅',
    'info': 'ℹ️',
    'help': '❓',
    'settings': '⚙️',
    'tune': '🎛️',
    'database': '💾',
    'cloud': '☁️',
    'wifi': '📶',
    'bluetooth': '🔵',
    'battery': '🔋',
    'signal': '📡',
    'location': '📍',
    'navigation': '🧭',
    'compass': '🧭',
    'target': '🎯',
    'flag': '🚩',
    'tag': '🏷️',
    'tags': '🏷️',
    'heart': '❤️',
    'heart-outline': '🤍',
    'like': '👍',
    'dislike': '👎',
    'comment': '💬',
    'message': '✉️',
    'chat': '💬',
    'send': '📤',
    'inbox': '📥',
    'archive': '📦',
    'trash': '🗑️',
    'restore': '♻️',
    'undo': '↶',
    'redo': '↷',
    'reply': '↩️',
    'forward': '↪️',
    'print': '🖨️',
    'save': '💾',
    'edit': '✏️',
    'create': '➕',
    'add': '➕',
    'remove': '➖',
    'subtract': '➖',
    'multiply': '✖️',
    'divide': '➗',
    'equal': '=',
    'percent': '%',
    'calculator': '🧮',
    'clock': '⏰',
    'timer': '⏱️',
    'stopwatch': '⏱️',
    'alarm': '⏰',
    'hourglass': '⏳',
    'calendar-today': '📅',
    'event': '📅',
    'schedule': '📅',
    'time': '🕐',
    'date': '📆',
    'month': '📅',
    'year': '📅',
    'week': '📅',
    'day': '☀️',
    'night': '🌙',
    'sunrise': '🌅',
    'sunset': '🌇',
    'weather': '🌤️',
    'sun': '☀️',
    'moon': '🌙',
    'cloud-outline': '☁️',
    'rain': '🌧️',
    'snow': '❄️',
    'wind': '💨',
    'thunder': '⚡',
    'fog': '🌫️',
  };

  const emoji = iconMap[name] || '•';
  
  return (
    <Text 
      style={[
        { 
          fontSize: size,
          color,
          lineHeight: size + 2,
        },
        style
      ]}
    >
      {emoji}
    </Text>
  );
}
